// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlineReferral_BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("New UI Changes for Online Referral")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class NewUIChangesForOnlineReferralFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "New UI Changes for Online Referral", "Online referral End to End Scenarios", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "New_UI_Changes_for_OnlineReferral.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/New_UI_Changes_for_OnlineReferral.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("[Verify that the user is able to see the new UI changes for online referral]")]
        [global::NUnit.Framework.TestCaseAttribute("UserFName", "UserLastName", "jayapradha.d@gainwelltechnologies.com", "9999999999", "Referring Source 1", "QA_Test", "5615 High Point Dr", "Unit 151029", "Irving", "TX", "75035", "Referral Type 1 - w/ Distribution Email", "Enumerated Provider", "123456789", "Tested by QA", "TestAutomation", "999999999.99", "02/13/2026", "02/13/2026", "02/13/2026", "TX", "Washington", "Yes", "TestReferralFN", "TestReferralLN", "Gainwell", "Referral party relationship to the involved party - Mapped to Dbl billing w/ dist" +
            "ribution", "HMS", "Mr", "FN", "MN", "LN", "Jr", "TestDesignation", "123-45-6789", "1234567890", "1234567890", "1234567890", "12-3456789", "1234567890", "1234567890", "1234567890", "Provider Type - Mapped to Dbl billing w/ distribution", "Provider Specialty - Mapped to Dbl billing w/ distribution", "Tester", "Test", "United States", "8888888888", "Yes", "No", "MemberFN", "MemberLN", "1234567", "02/13/1990", "Test", "No", "Test", "No", "Test", "No", "Test", "Texas", "0", null)]
        public async global::System.Threading.Tasks.Task VerifyThatTheUserIsAbleToSeeTheNewUIChangesForOnlineReferral(
                    string userFirstName, 
                    string userLastName, 
                    string emailAddress, 
                    string phoneNumber, 
                    string orgName, 
                    string title, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zipcode, 
                    string referralType, 
                    string involvedPartyType, 
                    string caseOrReferenceNumber, 
                    string detectedAs, 
                    string summary, 
                    string amount, 
                    string detectionDate, 
                    string incidentStartDate, 
                    string incidentEndDate, 
                    string state2, 
                    string city2, 
                    string witnessDropdown, 
                    string referralFN, 
                    string referralLN, 
                    string referralOrgname, 
                    string referralRelationship, 
                    string orgname, 
                    string namePrefix, 
                    string firstName, 
                    string middleName, 
                    string lastName, 
                    string nameSuffix, 
                    string designation, 
                    string sSN, 
                    string licenseNumber, 
                    string iDTest, 
                    string nPI, 
                    string tIN, 
                    string medicaidID, 
                    string medicareID, 
                    string otherID, 
                    string providerType, 
                    string providerSpecialty, 
                    string taxonomy, 
                    string other, 
                    string country, 
                    string fax, 
                    string rederralInvolveASpecificMemberDropdown, 
                    string isTheMemberTheSamePersonAsTheWitnessOrExternalReferringParty, 
                    string fN, 
                    string lN, 
                    string memberID, 
                    string dOB, 
                    string planType, 
                    string question1, 
                    string question2, 
                    string question3, 
                    string question4, 
                    string question5, 
                    string question6, 
                    string associatedstate, 
                    string @__pickleIndex, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserFirstName", userFirstName);
            argumentsOfScenario.Add("UserLastName", userLastName);
            argumentsOfScenario.Add("Email address", emailAddress);
            argumentsOfScenario.Add("Phone number", phoneNumber);
            argumentsOfScenario.Add("Org name", orgName);
            argumentsOfScenario.Add("title", title);
            argumentsOfScenario.Add("Address1", address1);
            argumentsOfScenario.Add("Address2", address2);
            argumentsOfScenario.Add("City", city);
            argumentsOfScenario.Add("State", state);
            argumentsOfScenario.Add("Zipcode", zipcode);
            argumentsOfScenario.Add("referralType", referralType);
            argumentsOfScenario.Add("involvedPartyType", involvedPartyType);
            argumentsOfScenario.Add("caseOrReferenceNumber", caseOrReferenceNumber);
            argumentsOfScenario.Add("detectedAs", detectedAs);
            argumentsOfScenario.Add("summary", summary);
            argumentsOfScenario.Add("amount", amount);
            argumentsOfScenario.Add("detectionDate", detectionDate);
            argumentsOfScenario.Add("incidentStartDate", incidentStartDate);
            argumentsOfScenario.Add("incidentEndDate", incidentEndDate);
            argumentsOfScenario.Add("state2", state2);
            argumentsOfScenario.Add("city2", city2);
            argumentsOfScenario.Add("witnessDropdown", witnessDropdown);
            argumentsOfScenario.Add("referralFN", referralFN);
            argumentsOfScenario.Add("referralLN", referralLN);
            argumentsOfScenario.Add("referralOrgname", referralOrgname);
            argumentsOfScenario.Add("referralRelationship", referralRelationship);
            argumentsOfScenario.Add("orgname", orgname);
            argumentsOfScenario.Add("name prefix", namePrefix);
            argumentsOfScenario.Add("first name", firstName);
            argumentsOfScenario.Add("middle name", middleName);
            argumentsOfScenario.Add("last name", lastName);
            argumentsOfScenario.Add("name suffix", nameSuffix);
            argumentsOfScenario.Add("designation", designation);
            argumentsOfScenario.Add("SSN", sSN);
            argumentsOfScenario.Add("licenseNumber", licenseNumber);
            argumentsOfScenario.Add("ID Test", iDTest);
            argumentsOfScenario.Add("NPI", nPI);
            argumentsOfScenario.Add("TIN", tIN);
            argumentsOfScenario.Add("medicaid ID", medicaidID);
            argumentsOfScenario.Add("Medicare ID", medicareID);
            argumentsOfScenario.Add("otherID", otherID);
            argumentsOfScenario.Add("provider type", providerType);
            argumentsOfScenario.Add("provider specialty", providerSpecialty);
            argumentsOfScenario.Add("Taxonomy", taxonomy);
            argumentsOfScenario.Add("other", other);
            argumentsOfScenario.Add("country", country);
            argumentsOfScenario.Add("fax", fax);
            argumentsOfScenario.Add("rederral involve a specific member dropdown", rederralInvolveASpecificMemberDropdown);
            argumentsOfScenario.Add("Is the member the same person as the witness or external referring party?", isTheMemberTheSamePersonAsTheWitnessOrExternalReferringParty);
            argumentsOfScenario.Add("FN", fN);
            argumentsOfScenario.Add("LN", lN);
            argumentsOfScenario.Add("memberID", memberID);
            argumentsOfScenario.Add("DOB", dOB);
            argumentsOfScenario.Add("planType", planType);
            argumentsOfScenario.Add("Question1", question1);
            argumentsOfScenario.Add("Question2", question2);
            argumentsOfScenario.Add("Question3", question3);
            argumentsOfScenario.Add("Question4", question4);
            argumentsOfScenario.Add("Question5", question5);
            argumentsOfScenario.Add("Question6", question6);
            argumentsOfScenario.Add("associatedstate", associatedstate);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("[Verify that the user is able to see the new UI changes for online referral]", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
 await testRunner.GivenAsync("when I open the Online referral application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
 await testRunner.AndAsync(string.Format("I enter the email as \"{0}\" on the Initial User Data Page", emailAddress), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
 await testRunner.AndAsync(string.Format("I enter the userFN as \"{0}\",User lastname as \"{1}\",Org name as \"{2}\",title as \"{3" +
                            "}\"  filled on the Initial User Data Page", userFirstName, userLastName, orgName, title), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.AndAsync(string.Format("I enter the Phone number as \"{0}\" on the Initial User Data Page", phoneNumber), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync(string.Format("I enter the \"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\", filled in the Address section yon the " +
                            "Initial User Data Page", address1, address2, city, state, zipcode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.WhenAsync("I click on the Next button on the Initial User Data Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
 await testRunner.WhenAsync("I should be navigated to the Next Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.WhenAsync(string.Format("Referral Type is selected as \"{0}\" on the second User Data Page", referralType), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
 await testRunner.AndAsync(string.Format("Suspect or Subject or Involved Party Type as \"{0}\"", involvedPartyType), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
 await testRunner.ThenAsync(string.Format("enter case or reference number as \"{0}\" on the second User Data Page", caseOrReferenceNumber), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
 await testRunner.AndAsync(string.Format("How was this detected as\"{0}\" ,please provide  a Summary of this referral as \"{1}" +
                            "\" on the second User Data Page", detectedAs, summary), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
 await testRunner.AndAsync(string.Format("enter Amount \"{0}\",detectiondate \"{1}\", incidentStartDate \"{2}\", incidentEndDate " +
                            "\"{3}\" on the second User Data Page", amount, detectionDate, incidentStartDate, incidentEndDate), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync(string.Format("enter state as \"{0}\" and city as \"{1}\" on the second User Data Page", state2, city2), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
 await testRunner.WhenAsync("I click on the Next button on the Initial User Data Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
 await testRunner.WhenAsync("I should be navigated to the Next Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
 await testRunner.WhenAsync(string.Format("Is thisInvolved Party dropdown is selected as \"{0}\" on the third User Data Page", witnessDropdown), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
 await testRunner.AndAsync(string.Format(@"enter InvolvedParty orgname as ""<associated orgname>"", name prefix as ""{0}"", associated party first name as ""<associated party first name>"",associated party middle name as ""<associated party middle name>"", associated party last name as ""<associated party last name>"" and name suffix as ""{1}"" on the fourth User Data Page", namePrefix, nameSuffix), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.AndAsync(string.Format("enter InvolvedParty Designation as \"{0}\",DOB as \"{1}\", SSN as \"{2}\", licenseNumbe" +
                            "r as \"{3}\", How witness or external party reported this as \"{4}\",any additional " +
                            "info as \"{5}\" ID Test as \"{6}\"", designation, dOB, sSN, licenseNumber, involvedPartyType, detectedAs, iDTest), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync(string.Format("enter InvolvedParty NPI as \"{0}\", TIN as \"{1}\",medicaid ID as \"{2}\",Medicare ID a" +
                            "s \"{3}\", otherID as \"{4}\" on the fourth User Data Page", nPI, tIN, medicaidID, medicareID, otherID), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
 await testRunner.AndAsync(string.Format("enter InvolvedParty provider type as \"{0}\", provider specialty as \"{1}\",Taxonomy " +
                            "as \"{2}\" and other as \"{3}\" on the fourth User Data Page", providerType, providerSpecialty, taxonomy, other), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
 await testRunner.AndAsync(string.Format("InvolvedParty street_Address_lineone as \"{0}\", street_Address_linetwo as \"{1}\", c" +
                            "ity as ,\"{2}\", state as \"{3}\" , county as \"{4}\" and zip code as \"{5}\"", address1, address2, city, associatedstate, city2, zipcode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
 await testRunner.AndAsync("InvolvedParty country as \"United States\",  phone number as \" 9999999999\", fax as " +
                        "\"8888888888\" and email address as \"jayapradha.d@gainwelltechnologies.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
 await testRunner.WhenAsync("I click on the Next button on the third User Data Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
 await testRunner.WhenAsync("I should be navigated to the Next Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
 await testRunner.AndAsync("is there anotherinvolved party dropdown is selected as \"No\" on the fourth User Da" +
                        "ta Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.WhenAsync(string.Format("Questionone Is this a resubmission as \"{0}\"", question1), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
 await testRunner.AndAsync(string.Format("Questiontwo as \"Question2\", QuestionThree as \"{0}\", Questionfour as \"{1}\", Questi" +
                            "onfive as \"{2}\", Questionsix as \"{3}\"", question3, question4, question5, question6), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
 await testRunner.AndAsync("then uploading a file using file path as \"C:/Users/jd/SourceQaDevelopment/Repos/F" +
                        "raudCapture_OnlineReferral/ReqnrollProject1/Attachments/TestFile.txt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.ThenAsync("click on proceed to next session button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
