// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OnlineReferral_BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Online Referral New UI Changes")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class OnlineReferralNewUIChangesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Online Referral New UI Changes", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "OnlineReferralNewChanges.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/OnlineReferralNewChanges.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Online Referral with IP-Involved Party Type-Associated Subject-Caregiver w/o req " +
            "fields and AIP-12.1.25 Non enumerated Individual")]
        [global::NUnit.Framework.TestCaseAttribute("Henry", "Welson", "yamuna.c@gainwelltechnologies.com", "MCO Example 1- Mapped to Enrollment Department", "123 Main St", "Florida", "Potential Fraud Referral", "Involved Party Type - Associated Subject- Caregiver w/o req fields", "test1", "test2", "Yes", "test1", "test2", "Yes", "12.1.25 Non enumerated Individual", "Yes", "asv", "Mr.", "Tommy", "Josh", "S", "Jr.", "Car Street", "456 StreetAddress4", "Texas", "11223", "Tester", "USA", "8974512631", "8974512645", "789065432", "234516", "josh@gmail.com", "test", "Test3", "Test4", "No", "Yes", "Test5", "Yes", "Test6", "Yes", "Test7", "TestFile.txt", "0", null)]
        public async global::System.Threading.Tasks.Task OnlineReferralWithIP_InvolvedPartyType_AssociatedSubject_CaregiverWOReqFieldsAndAIP_12_1_25NonEnumeratedIndividual(
                    string firstName, 
                    string lastName, 
                    string email, 
                    string organization, 
                    string streetAddress1, 
                    string stateName, 
                    string refType, 
                    string involvedPartyType, 
                    string detected, 
                    string referralSummary, 
                    string witness_Or_ExternalReferringParty, 
                    string report, 
                    string additionalInfo, 
                    string isAnotherInvolvedPartyAvailable, 
                    string additionalInvolvedPartyType, 
                    string isAnotherExternalInvolvedPartyAvailable, 
                    string organization1, 
                    string namePrefix, 
                    string firstName1, 
                    string middleName1, 
                    string lastName1, 
                    string nameSuffix, 
                    string streetAddress3, 
                    string streetAddress4, 
                    string city, 
                    string zip, 
                    string designation1, 
                    string country, 
                    string primaryPhone, 
                    string secondaryPhone, 
                    string ssn, 
                    string otherId, 
                    string email1, 
                    string other, 
                    string report1, 
                    string additionalInfo1, 
                    string isAnotherInvolvedPartyAvailable1, 
                    string question1, 
                    string question2, 
                    string question3, 
                    string question4, 
                    string question5, 
                    string question6, 
                    string filePath, 
                    string @__pickleIndex, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Organization", organization);
            argumentsOfScenario.Add("StreetAddress1", streetAddress1);
            argumentsOfScenario.Add("StateName", stateName);
            argumentsOfScenario.Add("RefType", refType);
            argumentsOfScenario.Add("InvolvedPartyType", involvedPartyType);
            argumentsOfScenario.Add("Detected", detected);
            argumentsOfScenario.Add("ReferralSummary", referralSummary);
            argumentsOfScenario.Add("witness_Or_ExternalReferringParty", witness_Or_ExternalReferringParty);
            argumentsOfScenario.Add("report", report);
            argumentsOfScenario.Add("additionalInfo", additionalInfo);
            argumentsOfScenario.Add("isAnotherInvolvedPartyAvailable", isAnotherInvolvedPartyAvailable);
            argumentsOfScenario.Add("additionalInvolvedPartyType", additionalInvolvedPartyType);
            argumentsOfScenario.Add("isAnotherExternalInvolvedPartyAvailable", isAnotherExternalInvolvedPartyAvailable);
            argumentsOfScenario.Add("Organization1", organization1);
            argumentsOfScenario.Add("NamePrefix", namePrefix);
            argumentsOfScenario.Add("FirstName1", firstName1);
            argumentsOfScenario.Add("MiddleName1", middleName1);
            argumentsOfScenario.Add("LastName1", lastName1);
            argumentsOfScenario.Add("NameSuffix", nameSuffix);
            argumentsOfScenario.Add("StreetAddress3", streetAddress3);
            argumentsOfScenario.Add("StreetAddress4", streetAddress4);
            argumentsOfScenario.Add("City", city);
            argumentsOfScenario.Add("Zip", zip);
            argumentsOfScenario.Add("Designation1", designation1);
            argumentsOfScenario.Add("Country", country);
            argumentsOfScenario.Add("PrimaryPhone", primaryPhone);
            argumentsOfScenario.Add("SecondaryPhone", secondaryPhone);
            argumentsOfScenario.Add("Ssn", ssn);
            argumentsOfScenario.Add("OtherId", otherId);
            argumentsOfScenario.Add("Email1", email1);
            argumentsOfScenario.Add("Other", other);
            argumentsOfScenario.Add("report1", report1);
            argumentsOfScenario.Add("additionalInfo1", additionalInfo1);
            argumentsOfScenario.Add("isAnotherInvolvedPartyAvailable1", isAnotherInvolvedPartyAvailable1);
            argumentsOfScenario.Add("question1", question1);
            argumentsOfScenario.Add("question2", question2);
            argumentsOfScenario.Add("question3", question3);
            argumentsOfScenario.Add("question4", question4);
            argumentsOfScenario.Add("question5", question5);
            argumentsOfScenario.Add("question6", question6);
            argumentsOfScenario.Add("filePath", filePath);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Online Referral with IP-Involved Party Type-Associated Subject-Caregiver w/o req " +
                    "fields and AIP-12.1.25 Non enumerated Individual", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await testRunner.GivenAsync("when I open the Online referral application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
 await testRunner.WhenAsync("i check the required fields in the \"Submitting Party Information\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
 await testRunner.WhenAsync("Required CSS glow appears with correct configured color controlled in Admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "Email",
                            "Organization",
                            "StreetAddress1"});
                table1.AddRow(new string[] {
                            string.Format("{0}", firstName),
                            string.Format("{0}", lastName),
                            string.Format("{0}", email),
                            string.Format("{0}", organization),
                            string.Format("{0}", streetAddress1)});
#line 7
 await testRunner.AndAsync("I filling the mandatory fileds details on the Initial User Data Page", ((string)(null)), table1, "And ");
#line hidden
#line 10
 await testRunner.ThenAsync("verify Dropdown lists are in alphabetical order", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "StateName"});
                table2.AddRow(new string[] {
                            string.Format("{0}", stateName)});
#line 11
 await testRunner.ThenAsync("select the StateName from the dropdown", ((string)(null)), table2, "Then ");
#line hidden
#line 14
 await testRunner.ThenAsync("Proceed to Email Address Verification", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
 await testRunner.AndAsync("I validate the Captcha for the email address verification page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "RefType",
                            "InvolvedPartyType"});
                table3.AddRow(new string[] {
                            string.Format("{0}", refType),
                            string.Format("{0}", involvedPartyType)});
#line 16
 await testRunner.AndAsync("I select the referralType and InvolvedPartyType from the dropdown", ((string)(null)), table3, "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Detected"});
                table4.AddRow(new string[] {
                            string.Format("{0}", detected)});
#line 19
 await testRunner.ThenAsync("I Enter the Text for How was this detected?", ((string)(null)), table4, "Then ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "ReferralSummary"});
                table5.AddRow(new string[] {
                            string.Format("{0}", referralSummary)});
#line 22
 await testRunner.ThenAsync("I Enter the Text for Please Provide a Summary of this Referral for the referral d" +
                        "etails page", ((string)(null)), table5, "Then ");
#line hidden
#line 25
 await testRunner.AndAsync("I click Next step to Proceed to the next page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "witness_Or_ExternalReferringParty"});
                table6.AddRow(new string[] {
                            string.Format("{0}", witness_Or_ExternalReferringParty)});
#line 26
 await testRunner.ThenAsync("I select involved party an external referring party or witness?", ((string)(null)), table6, "Then ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "report",
                            "additionalInfo"});
                table7.AddRow(new string[] {
                            string.Format("{0}", report),
                            string.Format("{0}", additionalInfo)});
#line 29
 await testRunner.ThenAsync("I enter the Text for How did this witness/external referring party report this? (" +
                        "Required) and Any Additonal Information regarding the witness or external referr" +
                        "ing party? (Optional)field", ((string)(null)), table7, "Then ");
#line hidden
#line 32
 await testRunner.AndAsync("I click \"Next\" Continue with Invloved Party Selection button to proceed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "isAnotherInvolvedPartyAvailable",
                            "additionalInvolvedPartyType",
                            "isAnotherExternalInvolvedPartyAvailable"});
                table8.AddRow(new string[] {
                            string.Format("{0}", isAnotherInvolvedPartyAvailable),
                            string.Format("{0}", additionalInvolvedPartyType),
                            string.Format("{0}", isAnotherExternalInvolvedPartyAvailable)});
#line 33
 await testRunner.ThenAsync("I select the another involved Party from the drop down menu", ((string)(null)), table8, "Then ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Organization1",
                            "NamePrefix",
                            "FirstName1",
                            "MiddleName1",
                            "LastName1",
                            "NameSuffix",
                            "StreetAddress3",
                            "StreetAddress4",
                            "City",
                            "Zip",
                            "Designation1",
                            "Country",
                            "PrimaryPhone",
                            "SecondaryPhone",
                            "Ssn",
                            "OtherId",
                            "Email1",
                            "Other"});
                table9.AddRow(new string[] {
                            string.Format("{0}", organization1),
                            string.Format("{0}", namePrefix),
                            string.Format("{0}", firstName1),
                            string.Format("{0}", middleName1),
                            string.Format("{0}", lastName1),
                            string.Format("{0}", nameSuffix),
                            string.Format("{0}", streetAddress3),
                            string.Format("{0}", streetAddress4),
                            string.Format("{0}", city),
                            string.Format("{0}", zip),
                            string.Format("{0}", designation1),
                            string.Format("{0}", country),
                            string.Format("{0}", primaryPhone),
                            string.Format("{0}", secondaryPhone),
                            string.Format("{0}", ssn),
                            string.Format("{0}", otherId),
                            string.Format("{0}", email1),
                            string.Format("{0}", other)});
#line 36
 await testRunner.ThenAsync("the following fields should be displayed:", ((string)(null)), table9, "Then ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "report1",
                            "additionalInfo1"});
                table10.AddRow(new string[] {
                            string.Format("{0}", report1),
                            string.Format("{0}", additionalInfo1)});
#line 39
 await testRunner.ThenAsync("I enter the Text for How did this witness/external referring party report this? (" +
                        "Required) and Any Additonal Information regarding the witness or external referr" +
                        "ing party? (Optional)field on Second Time", ((string)(null)), table10, "Then ");
#line hidden
#line 42
 await testRunner.AndAsync("I continue with Involved Party Selection and proceed to the next page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "isAnotherInvolvedPartyAvailable1"});
                table11.AddRow(new string[] {
                            string.Format("{0}", isAnotherInvolvedPartyAvailable1)});
#line 43
 await testRunner.ThenAsync("I Select the  another involved Party from the drop down menu as NO", ((string)(null)), table11, "Then ");
#line hidden
#line 46
 await testRunner.ThenAsync("I Click Finish Involved Party Selection and Proceed to Next Section button", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "question1",
                            "question2",
                            "question3",
                            "question4",
                            "question5",
                            "question6"});
                table12.AddRow(new string[] {
                            string.Format("{0}", question1),
                            string.Format("{0}", question2),
                            string.Format("{0}", question3),
                            string.Format("{0}", question4),
                            string.Format("{0}", question5),
                            string.Format("{0}", question6)});
#line 47
 await testRunner.AndAsync("I Select the Entering into the Questions and Attachments Section and answer the q" +
                        "uestions", ((string)(null)), table12, "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "filePath"});
                table13.AddRow(new string[] {
                            string.Format("{0}", filePath)});
#line 50
 await testRunner.ThenAsync("I add the Attachments with the help of Uploading the files and providing the deta" +
                        "il", ((string)(null)), table13, "Then ");
#line hidden
#line 53
 await testRunner.AndAsync("I Click Proceed to Next Section and Submit the Refreral button to proceed to Fini" +
                        "sh the Referral Submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
