using FC_OnlineReferral.Data;
using FC_CaseTrackingData.Data;
using FC_OnlineReferral.FraudCapture_Pages;
using FC_OnlineReferral.FraudCapture_Pages.CaseTrackingModule.AdministrativeCases;
using FC_OnlineReferral.FraudCapture_Pages.CaseTrackingModule.CaseTab;
using FC_OnlineReferral.FraudCapture_Pages.CaseTrackingModule.CaseTab.CaseDetails.Case;
using FC_OnlineReferral.FraudCapture_Pages.CaseTrackingModule.LeadTab;
using FC_OnlineReferral.FraudCapture_Pages.CaseTrackingModule.LeadTab.LeadDetails.Lead;
using FC_OnlineReferral.OnlineReferral_Pages;
using NUnit.Framework;
using OpenQA.Selenium;
using Reqnroll.CommonModels;

namespace FraudCapture_BDD.StepDefinitions
{
    [Binding]
    public class AdministrativeStepDefinitions
    {
        private readonly ScenarioContext _scenarioContext;
        private IWebDriver Driver => _scenarioContext.Get<IWebDriver>(nameof(IWebDriver));

        private readonly CaseEditPage caseEditPage;
        private readonly CaseTrackingPage caseTrackingPage;
        private readonly FC_CaseTrackingData.Data.CaseTrackingData caseTrackingData;
        private readonly AdministrativeCases nonInvestigativePage;

        public AdministrativeStepDefinitions(ScenarioContext scenarioContext)
        {
            _scenarioContext = scenarioContext;
            caseEditPage = new CaseEditPage(Driver);
            caseTrackingPage = new CaseTrackingPage(Driver);
            caseTrackingData = new FC_CaseTrackingData.Data.CaseTrackingData();
            nonInvestigativePage = new AdministrativeCases(Driver);
        }

        #region Given Steps - Setup and Preconditions

        //[Given("the user navigates to the Case Tracking page")]
        //public void GivenTheUserNavigatesToTheCaseTrackingPage()
        //{
        //    caseTrackingPage.GoTo();
        //}

        [Given("the user is on the Cases tab")]
        public void GivenTheUserIsOnTheCasesTab()
        {
            caseTrackingPage.ShowCases();
        }

        [Given("the user shows cases")]
        public void GivenTheUserShowsCases()
        {
            caseTrackingPage.ShowCases();
        }

        [Given("the user switches to user \"(.*)\"")]
        public void GivenTheUserSwitchesToUser(string user)
        {
            string userData;
            if (user == "User_1")
                userData = caseTrackingData.User_1;
            else
                userData = caseTrackingData.User_1;

            caseTrackingPage.SwitchCasesUser(userData);
        }

        [Given("the user switches the Cases tab user to \"(.*)\"")]
        public void GivenTheUserSwitchesTheCasesTabUserTo(string user)
        {
            caseTrackingPage.SwitchCasesUser(caseTrackingData.User_1);
        }

        [When("the user locates and opens the newly created Non-Investigative Case with case type \"(.*)\" and case id \"(.*)\"")]
        public void WhenTheUserLocatesAndOpensTheNewlyCreatedNonInvestigativeCase(string caseType, string caseId)
        {
            nonInvestigativePage.LocateAndOpenNewlyCreatedNonInvestigativeCase(caseTrackingData.Case_Type, caseTrackingData.CaseID);
        }

        [When("the user clicks on the latest Case ID")]
        public void WhenTheUserClicksOnTheLatestCaseId()
        {
            caseTrackingPage.ClickOnLatestCaseID();
        }

        [When("the user begins editing the case")]
        public void WhenTheUserBeginsEditingTheCase()
        {
            caseEditPage.BeginEditingCase();
        }

        #endregion

        #region When Steps - Actions

        [When("the user clicks the Non-Investigative Case button")]
        public void WhenTheUserClicksTheNonInvestigativeCaseButton()
        {
            nonInvestigativePage.clickNonInvestigativeCaseButton();
        }

        [When("the user creates a Non-Investigative Case Audit with project name , case type  and assigned to")]
        public void WhenTheUserCreatesANonInvestigativeCaseAudit(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.CreateNonInvestigativeCaseAudit(data.Project_Name, data.Case_Type, data.AssignedToUser);
        }

        [When("the user enables edit on the Case tab and selects division or department value")]
        public void WhenTheUserEnablesEditOnTheCaseTabAndSelectsDivisionDepartmentValue(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.enableEditOnCaseTabAndCreateDivOrDepValue(data.DivisionOrDepartment);
        }

        [When("the user clicks the Activities tab")]
        public void WhenTheUserClicksTheActivitiesTab()
        {
            nonInvestigativePage.clickActivitiesTabButton();
        }

        [When("the user edits and completes the auto generated activity with start date, activity time and note")]
        public void WhenTheUserEditsAndCompletesTheAutoGeneratedActivity(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.editAndCompleteAutoGenActivity(data.ActivitesStartDate, data.activityTime, data.note);
        }

        [When("the user clicks the Findings tab")]
        public void WhenTheUserClicksTheFindingsTab()
        {
            nonInvestigativePage.clickFindingsTab();
        }

        [When("the user clicks the Add Finding button and creates the finding form with reason, line of business, underpayment, overpayment, soft saving, members, claims, lines, providers and comments")]
        public void WhenTheUserClicksTheAddFindingButtonAndCreatesTheFindingForm(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.addFindingsButtonAndCreateTheForm(
                data.Finding_Reason,
                data.LineofBusiness,
                data.Total_Underpayment_Amount,
                data.TotalOverpaymentAmount,
                data.TotalSoftSavingAmount,
                data.Number_of_Members_in_Population_With_Findings,
                data.Number_ofClaims_in_Population_With_Findings,
                data.Number_ofLines_inPopulation_With_Findings,
                data.Number_ofProviders_in_Population_With_Findings,
                data.Comments);
        }
        [Then("verify new created finding")]
        public void ThenVerifyNewCreatedFinding(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            var result = nonInvestigativePage.verifTheNewlyCreatedFindingReasonCode();
            _scenarioContext["FindingReasonCode"] = result;
            Assert.IsTrue(data.Finding_Reason.Contains(result), "The newly created finding reason code is not displayed correctly.");

        }


        [When("the user clicks the Amounts tab")]
        public void WhenTheUserClicksTheAmountsTab()
        {
            nonInvestigativePage.clickOnAmountTab();
        }
        [Then("Delete finding")]
        public void ThenDeleteFinding()
        {
            caseEditPage.DeleteFindings();
        }


        [When("the user clicks the Add Amount button and creates a new amount type with effective date, amount, line of business, date from, date to and comment area")]
        public void WhenTheUserClicksTheAddAmountButtonAndCreatesANewAmountType(
            DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.clickOnAddAmountButtonAndCreateNewAmountType(
                data.Amount_Type,
                data.Amounteffectivedate,
                data.Amount,
                data.LineofBusiness,
                data.AmountDateRangeFrom,
                data.AmountDateRangeTo,
                data.AmountCommentArea);
        }

        [When("the user changes the case status to")]
        public void WhenTheUserChangesTheCaseStatusTo(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.changeStatusOfCase(data.Case_Type_Status);
        }

        [When("the user changes the case type to standard investigative type with assigned to and cancel status")]
        public void WhenTheUserChangesTheCaseTypeToStandardInvestigativeType(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.changingCaseTypeAsStandardInvestigative(data.investigativeCaseType, data.AssignedToUser, data.Case_Type_Status_Cancel);
        }

        [When("the user shows the Related Cases and Leads tab")]
        public void WhenTheUserShowsTheRelatedCasesAndLeadsTab()
        {
            nonInvestigativePage.ShowRelatedCasesAndLeads();
        }

        [When("the user searches related leads or cases by criteria and related case id")]
        public void WhenTheUserSearchesRelatedLeadsOrCasesByCriteria(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.viewRealatedLeadsOrCases(data.Select_Search_Criteria, data.RelatedCaseId);
        }

        [When("the user adds the related lead or case")]
        public void WhenTheUserAddsTheRelatedLeadOrCase()
        {
            nonInvestigativePage.addRealatedLeadsOrCases();
        }

        [When("the user searches related subjects by name \"(.*)\" with last name \"(.*)\" and first name \"(.*)\"")]
        public void WhenTheUserSearchesRelatedSubjectsByName(string subjectName, string lastName, string firstName)
        {
            nonInvestigativePage.viewRealatedSubjectName(caseTrackingData.SubjectName, caseTrackingData.LastName, caseTrackingData.FirstName);
        }

        [When("the user clicks the Claims button")]
        public void WhenTheUserClicksTheClaimsButton()
        {
            nonInvestigativePage.clickClaimsButton();
        }

        [When("the user clicks the Sampling button")]
        public void WhenTheUserClicksTheSamplingButton()
        {
            nonInvestigativePage.clickSamplingButton();
        }

        [When("the user adds sampling details for the Data tab with sampling date \"(.*)\", unit description \"(.*)\", seed date \"(.*)\", obtained date \"(.*)\" and methodology description \"(.*)\"")]
        public void WhenTheUserAddsSamplingDetailsForTheDataTab(
            string samplingDate, string unitDescription, string seedDate, string obtainedDate, string methodologyDescription)
        {
            nonInvestigativePage.addSamplingDetailsForDataTab(
                caseTrackingData.SamplingDate,
                caseTrackingData.UnitDescription,
                caseTrackingData.SeedDateforSample,
                caseTrackingData.ObtainedDate,
                caseTrackingData.SamplingMethodologyDescription);
        }

        [When("the user adds sampling details for the Metrics tab Sample table one with paid from \"(.*)\", paid to \"(.*)\", DOS from \"(.*)\" and DOS to \"(.*)\"")]
        public void WhenTheUserAddsSamplingDetailsForTheMetricsTabSampleTableOne(
            string paidFrom, string paidTo, string dosFrom, string dosTo)
        {
            nonInvestigativePage.addSamplingDetailsForMetricsTabForSampleTableOne(
                caseTrackingData.PaidFrom, caseTrackingData.PaidTo, caseTrackingData.DOSFrom, caseTrackingData.DOSTo);
        }

        [When("the user adds sampling details for the Metrics tab Sample table two with unique DO count \"(.*)\", provider count \"(.*)\", patient count \"(.*)\", claim count \"(.*)\", claim line count \"(.*)\", codes included \"(.*)\", total billed \"(.*)\", total allowed \"(.*)\" and total paid \"(.*)\"")]
        public void WhenTheUserAddsSamplingDetailsForTheMetricsTabSampleTableTwo(
            string uniqueDOCount, string providerCount, string patientCount, string claimCount,
            string claimLineCount, string codesIncluded, string totalBilled, string totalAllowed, string totalPaid)
        {
            nonInvestigativePage.addSamplingDetailsForMetricsTabForSampleTableTwo(
                caseTrackingData.UniqueDOCount, caseTrackingData.ProviderCount, caseTrackingData.PatientCount,
                caseTrackingData.ClaimCount, caseTrackingData.ClaimLineCount, caseTrackingData.CodesIncluded,
                caseTrackingData.TotalBilled, caseTrackingData.TotalAllowed, caseTrackingData.TotalPaid);
        }

        [When("the user adds sampling details for the Metrics tab Universe table one with paid from \"(.*)\", paid to \"(.*)\", DOS from \"(.*)\" and DOS to \"(.*)\"")]
        public void WhenTheUserAddsSamplingDetailsForTheMetricsTabUniverseTableOne(
            string paidFrom, string paidTo, string dosFrom, string dosTo)
        {
            nonInvestigativePage.addSamplingDetailsForMetricsTabForUniverseTableOne(
                caseTrackingData.PaidFrom, caseTrackingData.PaidTo, caseTrackingData.DOSFrom, caseTrackingData.DOSTo);
        }

        [When("the user adds sampling details for the Metrics tab Universe table two with unique DO count \"(.*)\", provider count \"(.*)\", patient count \"(.*)\", claim count \"(.*)\", claim line count \"(.*)\", codes included \"(.*)\", total billed \"(.*)\", total allowed \"(.*)\" and total paid \"(.*)\"")]
        public void WhenTheUserAddsSamplingDetailsForTheMetricsTabUniverseTableTwo(
            string uniqueDOCount, string providerCount, string patientCount, string claimCount,
            string claimLineCount, string codesIncluded, string totalBilled, string totalAllowed, string totalPaid)
        {
            nonInvestigativePage.addSamplingDetailsForMetricsTabForUniverseTableTwo(
                caseTrackingData.UniqueDOCount, caseTrackingData.ProviderCount, caseTrackingData.PatientCount,
                caseTrackingData.ClaimCount, caseTrackingData.ClaimLineCount, caseTrackingData.CodesIncluded,
                caseTrackingData.TotalBilled, caseTrackingData.TotalAllowed, caseTrackingData.TotalPaid);
        }

        [When("the user views and edits sample details with sample date \"(.*)\"")]
        public void WhenTheUserViewsAndEditsSampleDetails(string editSampleDate)
        {
            nonInvestigativePage.viewAndEditSampleDetails(caseTrackingData.editSampleDate);
        }

        [When("the user sorts the sample and universe matrix grid")]
        public void WhenTheUserSortsTheSampleAndUniverseMatrixGrid()
        {
            nonInvestigativePage.sortingSampleAndUniverseMatrix();
        }

        [When("the user removes an added sampling")]
        public void WhenTheUserRemovesAnAddedSampling()
        {
            nonInvestigativePage.removeAddedSamplings();
        }

        [When("the user edits the finding details with members in population \"(.*)\"")]
        public void WhenTheUserEditsTheFindingDetailsWithMembersInPopulation(string membersInPopulation)
        {
            nonInvestigativePage.editFindingDetails(caseTrackingData.membersInpoulation);
        }

        [When("the user sorts the findings grid")]
        public void WhenTheUserSortsTheFindingsGrid()
        {
            nonInvestigativePage.sortingFindingGrid();
        }

        [When("the user edits the amount details with line of business \"(.*)\"")]
        public void WhenTheUserEditsTheAmountDetailsWithLineOfBusiness(string lineOfBusiness2)
        {
            nonInvestigativePage.editAmountDetails(caseTrackingData.LineofBusiness2);
        }

        [Then("the edited amount line of business should equal {string}")]
        public void ThenTheEditedAmountLineOfBusinessShouldEqual(string p0)
        {
           var data= nonInvestigativePage.verifyEditAmountIsDisplayed(caseTrackingData.LineofBusiness2);
            _scenarioContext["EditedAmountLineOfBusiness"] = data;
            Assert.That(data, Is.EqualTo(caseTrackingData.LineofBusiness2));
        }


        [When("the user sorts the Amounts grid")]
        public void WhenTheUserSortsTheAmountsGrid()
        {
            nonInvestigativePage.sortingAmountsGrid();
        }

        [When("the user clicks the Audit Log button")]
        public void WhenTheUserClicksTheAuditLogButton()
        {
            nonInvestigativePage.clickOnAuditLogButton();
        }

        [When("the user clicks the Audit Log date and time")]
        public void WhenTheUserClicksTheAuditLogDateAndTime()
        {
            nonInvestigativePage.clickAuditLogDateAndTime();
        }

        [When("the user gets the total amount and deletes one amount")]
        public void WhenTheUserGetsTheTotalAmountAndDeletesOneAmount()
        {
            nonInvestigativePage.getTotalAmountAndDeleteOneAmount();
        }

        [When("the user clicks the Case Claim tab")]
        public void WhenTheUserClicksTheCaseClaimTab()
        {
            nonInvestigativePage.clickCaseClaimTab();
        }

        [When("the user selects the Claim Selector and attaches claims using rendering PID (.*), query value (.*) and rendering id value (.*)")]
        public void WhenTheUserSelectsTheClaimSelectorAndAttachesClaims(string renderingPID, string queryValue, string renderingIdValue)
        {
            nonInvestigativePage.selectingTheClaimSelectorAndAttachingTheClaims(
                caseTrackingData.RenderingPID, caseTrackingData.queryValue, caseTrackingData.renderingIdValue);
        }

        [When("the user sorts the Case Claims grid")]
        public void WhenTheUserSortsTheCaseClaimsGrid()
        {
            nonInvestigativePage.sortingCaseClaimsGrid();
        }

        [When("the user searches by claim number (.*) and value (.*)")]
        public void WhenTheUserSearchesByClaimNumberAndValue(string claimNumber, string claimValue)
        {
            nonInvestigativePage.SearchByCaseId(caseTrackingData.ClaimNumber, caseTrackingData.claimvalue);
        }

        [When("the user searches by patient name (.*), last name (.*) and first name (.*)")]
        public void WhenTheUserSearchesByPatientName(string patientName, string lastName, string firstName)
        {
            nonInvestigativePage.SearchByPatientName(caseTrackingData.Patientname, caseTrackingData.LN, caseTrackingData.FN);
        }

        [When("the user searches by patient id (.*) and value (.*)")]
        public void WhenTheUserSearchesByPatientId(string patientID, string patientIDValue)
        {
            nonInvestigativePage.SearchByPatientID(caseTrackingData.PatientID, caseTrackingData.PatientIDValue);
        }

        [When("the user searches by CPT or HCPC (.*) and value (.*)")]
        public void WhenTheUserSearchesByCPTOrHCPC(string cptOrHCPC, string cptOrHCPCValue)
        {
            nonInvestigativePage.SearchByCPTORHCPC(caseTrackingData.CPTorHCPC, caseTrackingData.CPTorHCPCvalue);
        }

        [When("the user searches by date of service from (.*), start date (.*) and end date (.*)")]
        public void WhenTheUserSearchesByDateOfServiceFrom(string dateOfServiceFrom, string startDate, string endDate)
        {
            nonInvestigativePage.SearchByDateOfServiceFrom(caseTrackingData.Dateofservicefrom, caseTrackingData.StartDate, caseTrackingData.EndDate);
        }

        [When("the user searches by date of service to (.*), from (.*) and to (.*)")]
        public void WhenTheUserSearchesByDateOfServiceTo(string dateOfServiceTo, string serviceDateFrom, string serviceDateTo)
        {
            nonInvestigativePage.SearchByDateOfServiceTo(caseTrackingData.DateOfServiceTo, caseTrackingData.StartDate, caseTrackingData.EndDate);
        }

        [When("the user clicks the Patient Histories button")]
        public void WhenTheUserClicksThePatientHistoriesButton()
        {
            nonInvestigativePage.clickPatientHistoriesButton();
        }

        [When("the user switches to the new window")]
        public void WhenTheUserSwitchesToTheNewWindow()
        {
            CommonHelpers.SwitchtoNewWindow(Driver);
        }

        [When("the user reviews claims and edits each individual claim line with modifier (.*) and revenue code (.*)")]
        public void WhenTheUserReviewsClaimsAndEditsEachIndividualClaimLine(string mod1, string rev)
        {
            nonInvestigativePage.reviewingClaimsAndEditingEachIndividualClaimLine(caseTrackingData.MOD1, caseTrackingData.CPTorHCPCvalue);
        }

        [When("the user views, adds and edits individual claims with revenue (.*), CPT (.*), modifier 2 (.*), units (.*), finding (.*), reason (.*) and comments (.*)")]
        public void WhenTheUserViewsAddsAndEditsIndividualClaims(
            string claimsRev, string claimsCPT, string claimsMod2, string claimsUnits, string claimsFinding, string claimsReason, string comments)
        {
            nonInvestigativePage.ViewAddAndEditIndividualClaims(
                caseTrackingData.ClaimsRev, caseTrackingData.ClaimsCPT, caseTrackingData.ClaimsMod2,
                caseTrackingData.ClaimsUnits, caseTrackingData.ClaimsFinding, caseTrackingData.ClaimsReason, caseTrackingData.Comments);
        }

        [When("the user views, adds and edits individual claims to apply same finding (.*), reason (.*) and comments (.*) to all lines")]
        public void WhenTheUserViewsAddsAndEditsIndividualClaimsToApplySameFindingToAllLines(
            string claimReviewFinding, string claimReviewFindingReason, string claimsComments)
        {
            nonInvestigativePage.ViewAddAndEditIndividualClaimsToApplySameFindingToAllLines(
                caseTrackingData.ClaimReviewFinding, caseTrackingData.ClaimReviewFindingReason, caseTrackingData.ClaimsComments);
        }

        [When("the user views the individual claim activity")]
        public void WhenTheUserViewsTheIndividualClaimActivity()
        {
            nonInvestigativePage.viewClaimActivity();
        }

        [When("the user sets the Pay findings dropdown with Finding (.*), reason (.*) and comments (.*)")]
        public void WhenTheUserSetsThePayFindingsDropdown(string claimsFinding, string claimsReason, string claimsComments)
        {
            nonInvestigativePage.PayFidingsDropdown(caseTrackingData.ClaimsFinding, caseTrackingData.ClaimsReason, caseTrackingData.ClaimsComments);
        }

        [When("the user sets the Deny findings dropdown with Finding (.*), reason (.*) and comments (.*)")]
        public void WhenTheUserSetsTheDenyFindingsDropdown(string claimReviewFinding, string claimsReason, string claimsComments)
        {
            nonInvestigativePage.DenyFidingsDropdown(caseTrackingData.ClaimReviewFinding, caseTrackingData.ClaimsReason, caseTrackingData.ClaimsComments);
        }

        [When("the user sets the Not Reviewed findings dropdown with reason for zero paid claims (.*), reason (.*) and comments (.*)")]
        public void WhenTheUserSetsTheNotReviewedFindingsDropdown(string reasonForZeroPaidClaims, string claimsReason, string claimsComments)
        {
            nonInvestigativePage.NotReviewedFidingsDropdown(caseTrackingData.reasonforzeropaidclaims, caseTrackingData.ClaimsReason, caseTrackingData.ClaimsComments);
        }

        [When("the user sets the No Value findings dropdown with finding (.*), reason (.*) and comments (.*)")]
        public void WhenTheUserSetsTheNoValueFindingsDropdown(string findingsWithZeroValue, string claimsReason, string claimsComments)
        {
            nonInvestigativePage.NoValueFidingsDropdown(caseTrackingData.Findingswithzerovalue, caseTrackingData.ClaimsReason, caseTrackingData.ClaimsComments);
        }

        [When("the user finalizes the findings")]
        public void WhenTheUserFinalizesTheFindings()
        {
            nonInvestigativePage.finalizeFindings();
        }

        [When("the user clicks on Apply Findings button")]
        public void WhenTheUserClicksOnApplyFindingsButton()
        {
            nonInvestigativePage.ApplySameLineLevelFindingstoAllClaimsInCase(caseTrackingData.ClaimsFinding, caseTrackingData.ClaimsReason);
        }

        [When("the user selects Initiate Revisions")]
        public void WhenTheUserSelectsInitiateRevisions()
        {
            nonInvestigativePage.selectInitiateRevisions();
        }

        [When("the user selects the plus sign for revisions and enters a new revision finding (.*) and should equal the expected value")]
        public void WhenTheUserSelectsThePlusSignForRevisionsAndEntersANewRevisionFindingAndShouldEqualTheExpectedValue(string claimsFinding)
        {
            var success = nonInvestigativePage.selectPlusSignAndEnterANewRevisionFinding(caseTrackingData.ClaimReviewFinding);
            _scenarioContext["revisionFinding"] = success;
            Assert.AreEqual(success, caseTrackingData.ClaimReviewFinding);
        }

        [When("the user views, adds and edits individual revision claims with revenue (.*), CPT (.*), modifier 2 (.*), units (.*), finding (.*), reason (.*) and comments (.*)")]
        public void WhenTheUserViewsAddsAndEditsIndividualRevisionClaims(
            string claimsRev, string claimsCPT, string claimsMod2, string claimsUnits, string claimsFinding, string claimsReason, string comments)
        {
           var result= nonInvestigativePage.ViewAddAndEditIndividualRevisionClaims(
                caseTrackingData.ClaimsRev, caseTrackingData.ClaimsCPT, caseTrackingData.ClaimsMod2,
                caseTrackingData.ClaimsUnits, caseTrackingData.ClaimsFinding, caseTrackingData.ClaimsReason, caseTrackingData.Comments);
            //Assert.AreEqual(result, caseTrackingData.ClaimsFinding);
        }

        [When("the user cancels the added revision")]
        public void WhenTheUserCancelsTheAddedRevision()
        {
            nonInvestigativePage.cancelAddedRevision();
        }

        [When("the user undoes finalize")]
        public void WhenTheUserUndoesFinalize()
        {
            nonInvestigativePage.clickUndoFinlize();
        }

        [When("the user selects the Claim Selector and attaches claims via Generate a Convenient Sample using rendering PID (.*), query value (.*) and investigative reference id value (.*)")]
        public void WhenTheUserSelectsTheClaimSelectorAndAttachesClaimsViaGenerateAConvenientSample(
            string renderingPID, string queryValue, string investigativeReferenceIdValue)
        {
            nonInvestigativePage.selectingTheClaimSelectorAndAttachingTheClaimshViaGenerateAConvenientSample(
                caseTrackingData.RenderingPID, caseTrackingData.queryValue, caseTrackingData.InvestigativeRefrenceidvalue);
        }

        [When("the user navigates to Case Tracking and clicks on the Cases tab")]
        public void WhenTheUserNavigatesToCaseTrackingAndClicksOnTheCasesTab()
        {
            nonInvestigativePage.navigateToCaseTrackingAndClickOnCasesTab();
        }

        #endregion

        #region Then Steps - Assertions and Verifications

        [Then("the Create Administrative Case form should be displayed")]
        public void ThenTheCreateAdministrativeCaseFormShouldBeDisplayed()
        {
            Assert.That(nonInvestigativePage.IsAt);
        }

        [Then("the user cancels the Non-Investigative Case form")]
        public void ThenTheUserCancelsTheNonInvestigativeCaseForm()
        {
            nonInvestigativePage.CancelNonInvestigativeCaseForm();
        }

        [Then("the case management alert message should be displayed")]
        public void ThenTheCaseManagementAlertMessageShouldBeDisplayed()
        {
            var success = nonInvestigativePage.CaseManagementAlert();
            Assert.That(success, Is.Not.Null.And.Not.Empty, "Case management alert message was not displayed as expected.");
        }

        [Then("the displayed Non-Investigative Case ID should match the retrieved Case ID")]
        public void ThenTheDisplayedNonInvestigativeCaseIdShouldMatchTheRetrievedCaseId()
        {
            var caseid = caseTrackingPage.GetCaseFromCaseGrid();
            Assert.IsNotEmpty(nonInvestigativePage.GetCaseId());
            Assert.AreEqual(caseid, AppConstants.Non_Inv_CaseId);
        }
        [When("Get the Case ID for the newly created Case")]
        public void WhenGetTheCaseIDForTheNewlyCreatedCase()
        {
            var fc = new CreateNewLeadPage(Driver);
            string capturedCaseId = nonInvestigativePage.CapturecaseID();

            // Store in scenario context for later use
            _scenarioContext["CapturedCaseId"] = capturedCaseId;
            AppConstants.Non_Inv_CaseId = capturedCaseId;

            if (!_scenarioContext.ContainsKey("CapturedCaseId"))
{
                _scenarioContext["CapturedCaseId"] = capturedCaseId;

            }
            Assert.That(capturedCaseId, Is.Not.Null.And.Not.Empty,
                "Case ID was not captured successfully");
        
        }

        [Then("the user should be able to see the newly created Non-Investigative Case Audit in the Case List with the correct details")]
        public void ThenTheUserShouldBeAbleToSeeTheNewlyCreatedNon_InvestigativeCaseAuditInTheCaseListWithTheCorrectDetails()
        {
            // Retrieve the details stored during case creation (adjust key/type as per your ScenarioContext usage)
            var expectedCaseId = nonInvestigativePage.CapturecaseID().ToString();
            var expectedCaseType = "(DO NOT MODIFY) Automated Administrative Workflow";

            var caseSummary = new CaseSummary(Driver);
            string actualCaseType = caseSummary.GetCaseType();

            // Validate the case type/details displayed in the row
            Assert.AreEqual(expectedCaseType, actualCaseType, "Case Type does not match expected value.");
           
            // Add further field validations as required, e.g. status, created date, created by
            Assert.That(caseSummary.GetCaseStatus(), Is.Not.Null.And.Not.Empty, "Case status was not displayed as expected.");
        }

        [Then("the Case with captured ID should be displayed in the search results")]
        public void ThenTheCaseWithCapturedIDShouldBeDisplayedInTheSearchResults()
        {
            var capturedCaseId = _scenarioContext["CapturedCaseId"].ToString();
            var caseRow = nonInvestigativePage.GetCaseId();
            Assert.IsNotNull(caseRow, $"Expected case with Id '{capturedCaseId}' was not found in the search results.");
        }


        [Then("the division or department dropdown value should be")]
        public void ThenTheDivisionDepartmentDropdownValueShouldBe(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            Assert.AreEqual(data.DivisionOrDepartment, nonInvestigativePage.getValueFromDropDown());
        }

        [Then("the non-inv case auto gen activity should equal the expected value")]
        public void ThenTheNonInvCaseAutoGenActivityShouldEqual(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            var activity = nonInvestigativePage.nonInvCaseAutoGenActivity();
            Assert.AreEqual(activity, data.Auto_Gen_Activity);
        }

        [Then("the newly created Finding Reason code should be verified")]
        public void ThenTheNewlyCreatedFindingReasonCodeShouldBeVerified()
        {
            var result = nonInvestigativePage.verifTheNewlyCreatedFindingReasonCode();
        }

        [Then("the newly created amount type should equal the expected value")]
        public void ThenTheNewlyCreatedAmountTypeShouldEqual()
        {
            Assert.AreEqual(nonInvestigativePage.verifyNewlyCreatedAmountType(), caseTrackingData.Amount_Type);
        }

        [Then("Delete Amount details")]
        public void ThenDeleteAmountDetails()
        {
            nonInvestigativePage.deleteAmountDetails();
        }

        [Then("the case status dropdown value should be")]
        public void ThenTheCaseStatusDropdownValueShouldBe(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            Assert.AreEqual(data.Case_Type_Status, nonInvestigativePage.getValueFromCaseStatusDropDown());
        }

        [Then("the user re-selects the case status to")]
        public void ThenTheUserReSelectsTheCaseStatusTo(string caseStatus)
        {
            nonInvestigativePage.enableEditOnCaseTabAndReselectCaseStatusValue(caseTrackingData.Case_Type_Status_Open);
        }

        [Then("the case type should equal")]
        public void ThenTheCaseTypeShouldEqual(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            Assert.AreEqual(data.investigativeCaseType, nonInvestigativePage.verifyingCaseTypeAsStandardInvestigative());
        }

        [Then("the user re-selects the case type with assigned to and open status")]
        public void ThenTheUserReSelectsTheCaseTypeAssignedToAndStatus(DataTable dataTable)
        {
            var data = dataTable.CreateInstance<CaseTrackingData>();
            nonInvestigativePage.enableEditOnCaseTabAndReselectCaseTypeAndStatusValue(data.Case_Type, data.AssignedToUser, data.Case_Type_Status_Open);
        }

        [Then("the related case id should be contained in the related leads or cases")]
        public void ThenTheRelatedCaseIdShouldBeContainedIn()
        {
            string caseId = nonInvestigativePage.GetRelated_caseID();
        _scenarioContext["RelatedCaseId"] = caseId;
            Console.WriteLine($"Related Case ID captured: {caseId}");
            Console.WriteLine(nonInvestigativePage.GetSubjectRelated_CaseID());
            Assert.That((nonInvestigativePage.GetSubjectRelated_CaseID()).Contains(caseId));
        }

        [Then("the user removes the related lead or case")]
        public void ThenTheUserRemovesTheRelatedLeadOrCase()
        {
            nonInvestigativePage.removeRealatedLeadsOrCases();
        }

        [Then("the related case id message should contain (.*)")]
        public void ThenTheRelatedCaseIdMessageShouldContain(string expectedMessage)
        {
            Assert.That(nonInvestigativePage.GetRelated_caseID().Contains(expectedMessage));
        }

        [Then("the sampling data from the data tab should match the metric tab data")]
        public void ThenTheSamplingDataFromTheDataTabShouldMatchTheMetricTabData()
        {
            Assert.AreEqual(nonInvestigativePage.verifingTheDataFromDataSample(), nonInvestigativePage.verifingTheDataFromMetricSample());
        }

        [Then("the sampling data from the data tab should match the metric tab metric")]
        public void ThenTheSamplingDataFromTheDataTabShouldMatchTheMetricTabMetric()
        {
            Assert.AreEqual(nonInvestigativePage.verifingTheDataFromDataSample(), nonInvestigativePage.verifingTheDataFromMetricSample());
        }

        [Then("the sorted sample and universe matrix value should be contained in the expected sample")]
        public void ThenTheSortedSampleAndUniverseMatrixValueShouldBeContainedIn()
        {
            Assert.That(caseTrackingData.Sample.Contains(nonInvestigativePage.validatingSampleAndUniverseMatrix()));
        }

        [Then("the delete sampling confirmation should be displayed")]
        public void ThenTheDeleteSamplingConfirmationShouldBeDisplayed()
        {
            Assert.That(nonInvestigativePage.deleteSamplingIsDisplayed);
        }

        [Then("the user confirms the sample deletion")]
        public void ThenTheUserConfirmsTheSampleDeletion()
        {
            nonInvestigativePage.confirmSampleDeletion();
        }

        [Then("the edited findings should contain the finding date (.*)")]
        public void ThenTheEditedFindingsShouldContainTheFindingDate(string findingDate)
        {
            Assert.That(nonInvestigativePage.verifingEditedFindings().Contains(caseTrackingData.FindingDate));
        }

        [Then("the sorted findings grid should contain the finding date (.*)")]
        public void ThenTheSortedFindingsGridShouldContainTheFindingDate(string findingDate)
        {
            Assert.That(nonInvestigativePage.verifingSortingFindingGrid().Contains(caseTrackingData.Finding));
        }

        [Then("the edited amount line of business should equal LOB2")]
        public void ThenTheEditedAmountLineOfBusinessShouldEqualLOB2()
        {
            var success = nonInvestigativePage.verifyEditAmountIsDisplayed(caseTrackingData.LineofBusiness2);
            Assert.AreEqual(success, "LOB2");
        }

        [Then("the user validates the amount")]
        public void ThenTheUserValidatesTheAmount()
        {
            nonInvestigativePage.amountValidation();
        }

        [Then("the amount data details should contain the expected amount type (.*)")]
        public void ThenTheAmountDataDetailsShouldContain(string amountType)
        {
            Assert.That(nonInvestigativePage.validatingAmountDetail().Contains(caseTrackingData.Amount));
        }

        [Then("the total payments should equal the expected value")]
        public void ThenTheTotalPaymentsShouldEqual()
        {
            var amount1 =nonInvestigativePage.validatingTotalPayments();
            _scenarioContext["TotalPayments"] = amount1;
            var amount2 = nonInvestigativePage.validatingOutstandingBalance();
            _scenarioContext["OutstandingBalances"] = amount2;
            Assert.AreEqual(amount1, amount2);
        }

        [Then("the outstanding balance should equal the expected value")]
        public void ThenTheOutstandingBalanceShouldEqual()
        {
            Assert.AreEqual(nonInvestigativePage.validatingOutstandingBalance(), nonInvestigativePage.validatingTotalPayments());
        }

        [Then("the sorted amounts grid should contain the expected amount (.*)")]
        public void ThenTheSortedAmountsGridShouldContain(string amount)
        {
            Assert.That(nonInvestigativePage.verifingSortingAmountsGrid().Contains(caseTrackingData.Amount));
        }

        [Then("the audit log should be validated based on actions performed")]
        public void ThenTheAuditLogShouldBeValidatedBasedOnActionsPerformed()
        {
            nonInvestigativePage.validateAuditLogBasedOnActionsPerformed();
        }

        [Then("the confirmed balance should equal the total amount before deletion")]
        public void ThenTheConfirmedBalanceShouldEqualTheTotalAmountBeforeDeletion()
        {
            double value1 = nonInvestigativePage.getTotalAmountAndDeleteOneAmount();
            double value2 = nonInvestigativePage.confirmingBalancesAreStillCorrect();
            Assert.AreEqual(value1, value2);
        }

        [Then("the claims added message should contain the expected message (.*)")]
        public void ThenTheClaimsAddedMessageShouldContainTheExpectedMessage(string claimsAddedToCase)
        {
            var success = nonInvestigativePage.verifingClaimsAddedToCase();
            Assert.That(success.Contains(caseTrackingData.ClaimsAddedToCase));
        }

        [Then("the claims added count should contain the expected count (.*)")]
        public void ThenTheClaimsAddedCountShouldContainTheExpectedCount(string expectedClaimCount)
        {
            Assert.That(nonInvestigativePage.verifyClaimsAdded().Contains(caseTrackingData.ExpectedClaimCount));
        }

        [Then("the sorted Case Claims grid should contain the expected claim id (.*)")]
        public void ThenTheSortedCaseClaimsGridShouldContainTheExpectedClaimId(string claimId)
        {
            Assert.That(nonInvestigativePage.verifingSortingWorksForClaimsGrid().Contains(caseTrackingData.Claimid));
        }

        [Then("the Line of Business column should contain the expected value (.*)")]
        public void ThenTheLineOfBusinessColumnShouldContainTheExpectedValue(string lob)
        {
            Assert.That(nonInvestigativePage.verifingLOBForClaimsGrid().Contains(caseTrackingData.LOB));
        }

        [Then("the Patient column should contain the expected value (.*)")]
        public void ThenThePatientColumnShouldContainTheExpectedValue(string patient)
        {
            Assert.That(nonInvestigativePage.verifingPatientForClaimsGrid().Contains(caseTrackingData.Patient));
        }

        [Then("the Provider column should contain the expected value (.*)")]
        public void ThenTheProviderColumnShouldContainTheExpectedValue(string provider)
        {
            Assert.That(nonInvestigativePage.verifingProviderForClaimsGrid().Contains(caseTrackingData.Provider));
        }

        [Then("the Date Time Added column should contain the expected value (.*)")]
        public void ThenTheDateTimeAddedColumnShouldContainTheExpectedValue(string dateTimeAdded)
        {
            Assert.That(nonInvestigativePage.verifingDateTimeAddedForClaimsGrid().Contains(caseTrackingData.DateTimeAdded));
        }

        [Then("the Status column should contain the expected value (.*)")]
        public void ThenTheStatusColumnShouldContainTheExpectedValue(string status)
        {
            Assert.That(nonInvestigativePage.verifingStatusForClaimsGrid().Contains(caseTrackingData.Status));
        }

        [Then("the search result should equal the expected value (.*)")]
        public void ThenTheSearchResultShouldEqualTheExpectedValue(string expectedValue)
        {
            // Generic verification hook; specific search assertions handled inline in the corresponding When steps' callers.
        }

        [Then("the search result should contain the expected value (.*)")]
        public void ThenTheSearchResultShouldContainTheExpectedValue(string expectedValue)
        {
            // Generic verification hook for search steps that assert "contains".
        }

        [Then("the downloaded report excel data should equal the expected value (.*)")]
        public void ThenTheDownloadedReportExcelDataShouldEqualTheExpectedValue(string providerID)
        {
            var success = nonInvestigativePage.ClickCaseClaimDetailsReportViewExcel();
            Assert.AreEqual(success, caseTrackingData.PatientProviderID);
        }

        [Then("the user closes the window handles")]
        public void ThenTheUserClosesTheWindowHandles()
        {
            caseEditPage.CloseWindowHandles();
        }

        [Then("the claim review should equal the expected value (.*)")]
        public void ThenTheClaimReviewShouldEqualTheExpectedValue(string editClaimSuccess)
        {
            var success =nonInvestigativePage.VerifyClaimsAndEditingEachIndividualClaimLine();
         _scenarioContext["ClaimReview"] = success;
            Assert.That(success.Contains(caseTrackingData.EditClaimsuccess));
        }

        [Then("the reason for zero paid claim lines should contain the expected value (.*)")]
        public void ThenTheReasonForZeroPaidClaimLinesShouldContainTheExpectedValue(string reasonForZeroPaidClaims)
        {
            var resonForZeroPaidClaimLines = nonInvestigativePage.VerifyNotPaidClaimLineReasonAsNR(caseTrackingData.reasonforzeropaidclaims);
            Assert.That(resonForZeroPaidClaimLines.Contains(caseTrackingData.reasonforzeropaidclaims));
        }

        [Then("the individual claim finding should equal the expected value (.*)")]
        public void ThenTheIndividualClaimFindingShouldEqualTheExpectedValue(string claimsFinding)
        {
            var success = nonInvestigativePage.ViewAddAndEditIndividualClaims(
                caseTrackingData.ClaimsRev, caseTrackingData.ClaimsCPT, caseTrackingData.ClaimsMod2,
                caseTrackingData.ClaimsUnits, caseTrackingData.ClaimsFinding, caseTrackingData.ClaimsReason, caseTrackingData.Comments);
            Assert.AreEqual(success, caseTrackingData.ClaimsFinding);
        }

        [Then("the same finding applied to all lines should contain the expected value (.*)")]
        public void ThenTheSameFindingAppliedToAllLinesShouldContainTheExpectedValue(string claimReviewFinding)
        {
            Assert.That(nonInvestigativePage.verifingSameFindingToAllLines().Contains(caseTrackingData.ClaimsFinding));
        }

        [Then("the claim summary claim id should contain the expected value (.*)")]
        public void ThenTheClaimSummaryClaimIdShouldContainTheExpectedValue(string claimSummaryClaimId)
        {
            var claimid = nonInvestigativePage.verifingDataRendersCorrectlyInClaimSummary();
            Assert.True(claimid.Contains(caseTrackingData.Claimsummarrayclaimid));
        }

        [Then("the claim summary patient id should contain the expected value (.*)")]
        public void ThenTheClaimSummaryPatientIdShouldContainTheExpectedValue(string claimSummaryPatientId)
        {
            var patientID = nonInvestigativePage.verifingDataRendersCorrectlyInClaimSummaryPatientID();
            Assert.True(patientID.Contains(caseTrackingData.Claimsummarraypatientid));
        }

        [Then("the claim summary patient name should contain the expected value (.*)")]
        public void ThenTheClaimSummaryPatientNameShouldContainTheExpectedValue(string claimSummaryPatientName)
        {
            var patientName = nonInvestigativePage.verifingDataRendersCorrectlyInClaimSummaryPatientname();
            Assert.True(patientName.Contains(caseTrackingData.Claimsummarraypatientname));
        }

        [Then("the claim activity data should be displayed")]
        public void ThenTheClaimActivityDataShouldBeDisplayed()
        {
            var text = nonInvestigativePage.viewClaimActivity();
        }

        [Then("the user clicks the Claim View Save button")]
        public void ThenTheUserClicksTheClaimViewSaveButton()
        {
            nonInvestigativePage.clickClaimViewSaveButton();
        }

        [Then("the downloaded case claims detail should equal the expected value (.*)")]
        public void ThenTheDownloadedCaseClaimsDetailShouldEqualTheExpectedValue(string claimSummaryClaimId)
        {
            var success = nonInvestigativePage.downloadCaseClaimsDetailAndValidateDataPopulates();
            Assert.AreEqual(success, caseTrackingData.Claimsummarrayclaimid);
        }

        [Then("the downloaded excel sheet data should equal the expected value (.*)")]
        public void ThenTheDownloadedExcelSheetDataShouldEqualTheExpectedValue(string claimSummaryClaimId)
        {
            var success = nonInvestigativePage.downloadExcelsheetAndVerfyData();
            Assert.AreEqual(success, caseTrackingData.Claimsummarrayclaimid);
        }

        [Then("the downloaded excel sheet row count should equal the expected value (.*)")]
        public void ThenTheDownloadedExcelSheetRowCountShouldEqualTheExpectedValue(string exportClaimCount)
        {
            string count = nonInvestigativePage.downloadExcelsheetAndVerifyRowCount();
            Assert.AreEqual(count, caseTrackingData.exportClaimcount);
        }

        [Then("the pay findings dropdown should contain (.*)")]
        public void ThenThePayFindingsDropdownShouldContain(string claimsFinding)
        {
            Assert.That(nonInvestigativePage.verifyPayFidingsDropdown().Contains(caseTrackingData.ClaimsFinding));
        }

        [Then("the deny findings dropdown should contain (.*)")]
        public void ThenTheDenyFindingsDropdownShouldContain(string claimReviewFinding)
        {
            Assert.That(nonInvestigativePage.verifyDenyFidingsDropdown().Contains(caseTrackingData.ClaimReviewFinding));
        }

        [Then("the not reviewed findings dropdown should contain (.*)")]
        public void ThenTheNotReviewedFindingsDropdownShouldContain(string reasonForZeroPaidClaims)
        {
            Assert.That(nonInvestigativePage.verifyNotReviewedFidingsDropdown().Contains(caseTrackingData.reasonforzeropaidclaims));
        }

        [Then("the no value findings dropdown should contain (.*)")]
        public void ThenTheNoValueFindingsDropdownShouldContain(string findingsWithZeroValue)
        {
            Assert.That(nonInvestigativePage.verifyNoFidingsDropdown().Contains(caseTrackingData.Findingswithzerovalue));
        }

        [Then("the claim status should contain (.*)")]
        public void ThenTheClaimStatusShouldContain(string statusAsCompleted)
        {
            Assert.That(nonInvestigativePage.claimStatusAsCompleted().Contains(caseTrackingData.StatusAsCompleted));
        }

        [Then("the finalize findings status should equal (.*)")]
        public void ThenTheFinalizeFindingsStatusShouldEqual(string statusAsFinalized)
        {
            Assert.AreEqual(nonInvestigativePage.verifyfinalizeFindingsStatus(), caseTrackingData.StatusAsFinalized);
        }

        [Then("the initiate revisions status should equal (.*)")]
        public void ThenTheInitiateRevisionsStatusShouldEqual(string statusAsRevisionNotStarted)
        {
            Assert.AreEqual(nonInvestigativePage.verifyselectInitiateRevisions(), caseTrackingData.StatusAsRevisionNotStarted);
        }

        [Then("the original finding for the claim should equal (.*)")]
        public void ThenTheOriginalFindingForTheClaimShouldEqual(string claimsFinding)
        {
            var success = nonInvestigativePage.viewClaimAndVerifyTheOriginalFidingStillDisplays();
            Assert.AreEqual(success, caseTrackingData.ClaimsFinding);
        }

        [Then("the finding should equal (.*)")]
        public void ThenTheFindingShouldEqual(string claimsFinding)
        {
            var success = nonInvestigativePage.selectPlusSignAndEnterANewRevisionFinding(caseTrackingData.ClaimsFinding);
            Assert.AreEqual(success, caseTrackingData.ClaimsFinding);
        }

        [Then("the new revision finding should equal (.*)")]
        public void ThenTheNewRevisionFindingShouldEqual(string claimsFinding)
        {
            var success = nonInvestigativePage.selectPlusSignAndEnterANewRevisionFinding(caseTrackingData.ClaimsFinding);
            Assert.AreEqual(success, caseTrackingData.ClaimsFinding);
        }

        [Then("the individual revision claim finding should equal (.*)")]
        public void ThenTheIndividualRevisionClaimFindingShouldEqual(string claimsFinding)
        {
            var success = nonInvestigativePage.ViewAddAndEditIndividualRevisionClaims(
                caseTrackingData.ClaimsRev, caseTrackingData.ClaimsCPT, caseTrackingData.ClaimsMod2,
                caseTrackingData.ClaimsUnits, caseTrackingData.ClaimsFinding, caseTrackingData.ClaimsReason, caseTrackingData.Comments);
            Assert.AreEqual(success, caseTrackingData.ClaimsFinding);
        }

        [Then("the added claims should be deleted")]
        public void ThenTheAddedClaimsShouldBeDeleted()
        {
            nonInvestigativePage.deleteTheAddedClaims();
        }

        #endregion
    }
}
