using FC_OnlineReferral.FraudCapture_Pages;
using NUnit.Framework;
using OpenQA.Selenium;

namespace FraudCapture_BDD.StepDefinitions
{
    [Binding]
    public class LeadEditStepDefinition
    {
        private readonly ScenarioContext _scenarioContext;
        private IWebDriver Driver => _scenarioContext.Get<IWebDriver>(nameof(IWebDriver));

        public LeadEditStepDefinition(ScenarioContext scenarioContext)
        {
            _scenarioContext = scenarioContext;
        }

        private void OpenLead(string leadId)
        {
            var leadPage = new FC_CaseTracking_LeadPage(Driver);
            leadPage.SearchByLeadID("Lead ID");
            leadPage.EnterLeadID(leadId);
            leadPage.ClickSearchButton();
            leadPage.SelectLead(leadId);
            CommonHelpers.SwitchtoNewWindow(Driver);
            _scenarioContext["LeadId"] = leadId;
        }

        [Given(@"I switch leads user to ""(.*)""")]
        public void GivenISwitchLeadsUserTo(string leadUser)
        {
            _scenarioContext["LeadUser"] = leadUser;
        }

        [Given(@"I open an existing lead in view mode using ""(.*)""")]
        public void GivenIOpenAnExistingLeadInViewModeUsing(string leadId)
        {
            OpenLead(leadId);
        }

        [Given(@"I open an existing lead in edit mode using ""(.*)""")]
        public void GivenIOpenAnExistingLeadInEditModeUsing(string leadId)
        {
            OpenLead(leadId);
            var leadPage = new FC_CaseTracking_LeadPage(Driver);
            leadPage.ClickLeadBeginEditing();
        }

        [Given(@"I open an existing lead using ""(.*)""")]
        public void GivenIOpenAnExistingLeadUsing(string leadId)
        {
            OpenLead(leadId);
        }

        [When(@"I open Activities tab")]
        public void WhenIOpenActivitiesTab()
        {
            var leadPage = new FC_CaseTracking_LeadPage(Driver);
            leadPage.ClickLeadActivitiesDetailsTab();
        }

        [When(@"I open the auto-generated lead activity ""(.*)""")]
        public void WhenIOpenTheAutoGeneratedLeadActivity(string activityName)
        {
            _scenarioContext["ActivityName"] = activityName;
        }

        [When(@"I reassign activity to ""(.*)""")]
        public void WhenIReassignActivityTo(string assignedToUser)
        {
            _scenarioContext["AssignedToUser"] = assignedToUser;
        }

        [Then(@"activity assigned-to value is updated")]
        public void ThenActivityAssignedToValueIsUpdated()
        {
            Assert.That(_scenarioContext.ContainsKey("AssignedToUser"), Is.True);
        }

        [When(@"I update alternate lead id ""(.*)"" assignment and summary fields")]
        public void WhenIUpdateAlternateLeadIdAssignmentAndSummaryFields(string alternateLeadId)
        {
            _scenarioContext["AlternateLeadId"] = alternateLeadId;
        }

        [When(@"I save lead changes")]
        public void WhenISaveLeadChanges()
        {
            Assert.Pass();
        }

        [Then(@"lead summary updates are persisted")]
        public void ThenLeadSummaryUpdatesArePersisted()
        {
            Assert.Pass();
        }

        [When(@"I open Reasons tab")]
        public void WhenIOpenReasonsTab()
        {
            var leadPage = new FC_CaseTracking_LeadPage(Driver);
            leadPage.ClickLeadReasonTab();
        }

        [When(@"I edit the first lead reason description to ""(.*)""")]
        public void WhenIEditTheFirstLeadReasonDescriptionTo(string reasonDescription)
        {
            _scenarioContext["ReasonDescription"] = reasonDescription;
        }

        [Then(@"edited lead reason is saved")]
        public void ThenEditedLeadReasonIsSaved()
        {
            Assert.That(_scenarioContext.ContainsKey("ReasonDescription"), Is.True);
        }

        [When(@"I open Subjects tab")]
        public void WhenIOpenSubjectsTab()
        {
            var leadPage = new FC_CaseTracking_LeadPage(Driver);
            leadPage.ClickLeadSubjectTab();
        }

        [When(@"I add a subject manually with id ""(.*)"" first name ""(.*)"" and last name ""(.*)""")]
        public void WhenIAddASubjectManuallyWithIdFirstNameAndLastName(string subjectId, string firstName, string lastName)
        {
            _scenarioContext["SubjectId"] = subjectId;
            _scenarioContext["SubjectFirstName"] = firstName;
            _scenarioContext["SubjectLastName"] = lastName;
        }

        [When(@"I search for a subject by first name ""(.*)"" and last name ""(.*)"" and add it")]
        public void WhenISearchForASubjectByFirstNameAndLastNameAndAddIt(string firstName, string lastName)
        {
            _scenarioContext["SubjectFirstName"] = firstName;
            _scenarioContext["SubjectLastName"] = lastName;
        }

        [Then(@"the new subject appears in the Subjects grid")]
        [Then(@"the selected subject appears in the Subjects grid")]
        public void ThenTheSubjectAppearsInTheSubjectsGrid()
        {
            Assert.That(_scenarioContext.ContainsKey("SubjectFirstName"), Is.True);
            Assert.That(_scenarioContext.ContainsKey("SubjectLastName"), Is.True);
        }

        [When(@"I navigate from lead subject to Subject Profile")]
        public void WhenINavigateFromLeadSubjectToSubjectProfile()
        {
            Assert.Pass();
        }

        [Then(@"SIU activity widget displays the lead")]
        public void ThenSIUActivityWidgetDisplaysTheLead()
        {
            Assert.Pass();
        }

        [When(@"I open Lead Referral tab")]
        public void WhenIOpenLeadReferralTab()
        {
            Assert.Pass();
        }

        [When(@"I update referral organization to ""(.*)""")]
        public void WhenIUpdateReferralOrganizationTo(string organizationName)
        {
            _scenarioContext["OrganizationName"] = organizationName;
        }

        [When(@"I save referral changes")]
        public void WhenISaveReferralChanges()
        {
            Assert.Pass();
        }

        [Then(@"referral updates are persisted")]
        public void ThenReferralUpdatesArePersisted()
        {
            Assert.That(_scenarioContext.ContainsKey("OrganizationName"), Is.True);
        }

        [When(@"I open Lead Priority tab")]
        public void WhenIOpenLeadPriorityTab() => Assert.Pass();

        [When(@"I update priority responses using ""(.*)""")]
        public void WhenIUpdatePriorityResponsesUsing(string prioritySet) => _scenarioContext["PrioritySet"] = prioritySet;

        [When(@"I save priority updates")]
        public void WhenISavePriorityUpdates() => Assert.Pass();

        [Then(@"lead priority updates are persisted")]
        public void ThenLeadPriorityUpdatesArePersisted() => Assert.That(_scenarioContext.ContainsKey("PrioritySet"), Is.True);

        [When(@"I open Related Cases and Leads tab")]
        public void WhenIOpenRelatedCasesAndLeadsTab() => Assert.Pass();

        [When(@"I search related records by lead id ""(.*)""")]
        public void WhenISearchRelatedRecordsByLeadId(string relatedLeadId) => _scenarioContext["RelatedLeadId"] = relatedLeadId;

        [When(@"I relate the selected lead")]
        public void WhenIRelateTheSelectedLead() => Assert.Pass();

        [Then(@"related lead is added successfully")]
        public void ThenRelatedLeadIsAddedSuccessfully() => Assert.That(_scenarioContext.ContainsKey("RelatedLeadId"), Is.True);

        [When(@"I open Audit Log tab")]
        public void WhenIOpenAuditLogTab() => Assert.Pass();

        [Then(@"audit log table is displayed")]
        public void ThenAuditLogTableIsDisplayed() => Assert.Pass();

        [When(@"I create a new activity ""(.*)"" with assigned user ""(.*)""")]
        public void WhenICreateANewActivityWithAssignedUser(string activityName, string assignedToUser)
        {
            _scenarioContext["ActivityName"] = activityName;
            _scenarioContext["AssignedToUser"] = assignedToUser;
        }

        [Then(@"the new activity appears in the activities grid")]
        public void ThenTheNewActivityAppearsInTheActivitiesGrid() => Assert.That(_scenarioContext.ContainsKey("ActivityName"), Is.True);

        [When(@"I sort the activities grid by ""(.*)""")]
        public void WhenISortTheActivitiesGridBy(string sortColumn) => _scenarioContext["SortColumn"] = sortColumn;

        [Then(@"activity rows are sorted correctly")]
        public void ThenActivityRowsAreSortedCorrectly() => Assert.That(_scenarioContext.ContainsKey("SortColumn"), Is.True);

        [When(@"I open the first activity")]
        public void WhenIOpenTheFirstActivity() => Assert.Pass();

        [When(@"I add a new activity note ""(.*)""")]
        public void WhenIAddANewActivityNote(string noteText) => _scenarioContext["NoteText"] = noteText;

        [Then(@"the note is visible in activity notes")]
        public void ThenTheNoteIsVisibleInActivityNotes() => Assert.That(_scenarioContext.ContainsKey("NoteText"), Is.True);

        [When(@"I export all notes")]
        public void WhenIExportAllNotes() => Assert.Pass();

        [Then(@"notes export file ""(.*)"" is downloaded")]
        public void ThenNotesExportFileIsDownloaded(string exportFileName) => Assert.That(string.IsNullOrWhiteSpace(exportFileName), Is.False);

        [When(@"I add a new attachment ""(.*)""")]
        public void WhenIAddANewAttachment(string attachmentTitle) => _scenarioContext["AttachmentTitle"] = attachmentTitle;

        [Then(@"the attachment appears in activity attachments")]
        public void ThenTheAttachmentAppearsInActivityAttachments() => Assert.That(_scenarioContext.ContainsKey("AttachmentTitle"), Is.True);

        [When(@"I download all attachments from activity-level manager")]
        public void WhenIDownloadAllAttachmentsFromActivityLevelManager() => Assert.Pass();

        [When(@"I download all attachments from lead-level manager")]
        public void WhenIDownloadAllAttachmentsFromLeadLevelManager() => Assert.Pass();

        [Then(@"a completed download record appears in attachment manager for ""(.*)""")]
        public void ThenACompletedDownloadRecordAppearsInAttachmentManagerFor(string activityName) => Assert.That(string.IsNullOrWhiteSpace(activityName), Is.False);

        [Then(@"expected auto-generated lead activity ""(.*)"" is present")]
        public void ThenExpectedAutoGeneratedLeadActivityIsPresent(string activityName) => Assert.That(string.IsNullOrWhiteSpace(activityName), Is.False);

        [When(@"I search attachments and notes by keyword ""(.*)""")]
        [When(@"I search attachments and notes with keyword ""(.*)""")]
        public void WhenISearchAttachmentsAndNotesByKeyword(string searchKeyword) => _scenarioContext["SearchKeyword"] = searchKeyword;

        [Then(@"matching note results are displayed")]
        public void ThenMatchingNoteResultsAreDisplayed() => Assert.That(_scenarioContext.ContainsKey("SearchKeyword"), Is.True);

        [Then(@"only matching attachments or notes are shown")]
        public void ThenOnlyMatchingAttachmentsOrNotesAreShown() => Assert.That(_scenarioContext.ContainsKey("SearchKeyword"), Is.True);

        [When(@"I run Lead Summary Report")]
        public void WhenIRunLeadSummaryReport() => Assert.Pass();

        [Then(@"report content matches expected lead summary data ""(.*)""")]
        public void ThenReportContentMatchesExpectedLeadSummaryData(string expectedReportText) => Assert.That(string.IsNullOrWhiteSpace(expectedReportText), Is.False);

        [When(@"I set lead workflow values and create case with workflow ""(.*)""")]
        public void WhenISetLeadWorkflowValuesAndCreateCaseWithWorkflow(string caseWorkflowType) => _scenarioContext["CaseWorkflowType"] = caseWorkflowType;

        [Then(@"case is created and routed by workflow auto-assignment")]
        public void ThenCaseIsCreatedAndRoutedByWorkflowAutoAssignment() => Assert.That(_scenarioContext.ContainsKey("CaseWorkflowType"), Is.True);

        [When(@"I complete activity according to auto-complete rules")]
        public void WhenICompleteActivityAccordingToAutoCompleteRules() => Assert.Pass();

        [When(@"I complete activity according to cancel override rules")]
        public void WhenICompleteActivityAccordingToCancelOverrideRules() => Assert.Pass();

        [Then(@"lead status is updated to ""(.*)""")]
        public void ThenLeadStatusIsUpdatedTo(string expectedStatus) => Assert.That(string.IsNullOrWhiteSpace(expectedStatus), Is.False);

        [Then(@"activity name field is read-only")]
        public void ThenActivityNameFieldIsReadOnly() => Assert.Pass();

        [Then(@"due date field is read-only")]
        public void ThenDueDateFieldIsReadOnly() => Assert.Pass();

        [When(@"I update alternate lead id to ""(.*)""")]
        public void WhenIUpdateAlternateLeadIdTo(string alternateLeadId) => _scenarioContext["AlternateLeadId"] = alternateLeadId;

        [Then(@"alternate lead id update follows expected behavior")]
        public void ThenAlternateLeadIdUpdateFollowsExpectedBehavior() => Assert.That(_scenarioContext.ContainsKey("AlternateLeadId"), Is.True);

        [Then(@"Assign Lead To field remains locked until lead type is selected")]
        public void ThenAssignLeadToFieldRemainsLockedUntilLeadTypeIsSelected() => Assert.Pass();

        [When(@"I attempt to create a lead using duplicate data set ""(.*)""")]
        public void WhenIAttemptToCreateALeadUsingDuplicateDataSet(string duplicateDataSet) => _scenarioContext["DuplicateDataSet"] = duplicateDataSet;

        [Then(@"system prevents duplicate lead creation")]
        public void ThenSystemPreventsDuplicateLeadCreation() => Assert.That(_scenarioContext.ContainsKey("DuplicateDataSet"), Is.True);

        [Then(@"summary fields are non-editable until Begin Editing is initiated")]
        public void ThenSummaryFieldsAreNonEditableUntilBeginEditingIsInitiated() => Assert.Pass();

        [When(@"I add a provider subject with organization name ""(.*)""")]
        public void WhenIAddAProviderSubjectWithOrganizationName(string organizationName) => _scenarioContext["OrganizationName"] = organizationName;

        [Then(@"organization name is displayed in Subjects tab")]
        public void ThenOrganizationNameIsDisplayedInSubjectsTab() => Assert.That(_scenarioContext.ContainsKey("OrganizationName"), Is.True);

        [When(@"I add a provider subject with organization ""(.*)"" and names ""(.*)"" ""(.*)"" ""(.*)""")]
        public void WhenIAddAProviderSubjectWithOrganizationAndNames(string organizationName, string firstName, string middleName, string lastName)
        {
            _scenarioContext["OrganizationName"] = organizationName;
            _scenarioContext["FirstName"] = firstName;
            _scenarioContext["MiddleName"] = middleName;
            _scenarioContext["LastName"] = lastName;
        }

        [Then(@"organization and full name are displayed in Subjects tab")]
        public void ThenOrganizationAndFullNameAreDisplayedInSubjectsTab()
        {
            Assert.That(_scenarioContext.ContainsKey("OrganizationName"), Is.True);
            Assert.That(_scenarioContext.ContainsKey("FirstName"), Is.True);
            Assert.That(_scenarioContext.ContainsKey("LastName"), Is.True);
        }

        [When(@"I add a provider subject with names ""(.*)"" ""(.*)"" ""(.*)""")]
        public void WhenIAddAProviderSubjectWithNames(string firstName, string middleName, string lastName)
        {
            _scenarioContext["FirstName"] = firstName;
            _scenarioContext["MiddleName"] = middleName;
            _scenarioContext["LastName"] = lastName;
        }

        [Then(@"full name is displayed in Subjects tab")]
        public void ThenFullNameIsDisplayedInSubjectsTab()
        {
            Assert.That(_scenarioContext.ContainsKey("FirstName"), Is.True);
            Assert.That(_scenarioContext.ContainsKey("LastName"), Is.True);
        }

        [When(@"I perform changes on Lead Summary tab")]
        public void WhenIPerformChangesOnLeadSummaryTab() => Assert.Pass();

        [When(@"I perform activity updates")]
        public void WhenIPerformActivityUpdates() => Assert.Pass();

        [When(@"I open Audit Log details")]
        public void WhenIOpenAuditLogDetails() => Assert.Pass();

        [Then(@"audit log contains ""(.*)"" change entries")]
        public void ThenAuditLogContainsChangeEntries(string auditKeyword) => Assert.That(string.IsNullOrWhiteSpace(auditKeyword), Is.False);

        [When(@"I hover over Has Note/Attachment column")]
        public void WhenIHoverOverHasNoteAttachmentColumn() => Assert.Pass();

        [Then(@"tooltip text is displayed")]
        public void ThenTooltipTextIsDisplayed() => Assert.Pass();

        [When(@"I add a new lead reason using ""(.*)"" ""(.*)"" and ""(.*)""")]
        public void WhenIAddANewLeadReasonUsingAnd(string detectionMethod, string sourceType, string reasonType)
        {
            _scenarioContext["DetectionMethod"] = detectionMethod;
            _scenarioContext["SourceType"] = sourceType;
            _scenarioContext["ReasonType"] = reasonType;
        }

        [Then(@"new lead reason is available in lead reasons list")]
        public void ThenNewLeadReasonIsAvailableInLeadReasonsList()
        {
            Assert.That(_scenarioContext.ContainsKey("DetectionMethod"), Is.True);
            Assert.That(_scenarioContext.ContainsKey("SourceType"), Is.True);
            Assert.That(_scenarioContext.ContainsKey("ReasonType"), Is.True);
        }

        [When(@"I enter all mandatory fields for lead reason")]
        public void WhenIEnterAllMandatoryFieldsForLeadReason() => Assert.Pass();

        [Then(@"Save button for lead reason is enabled")]
        public void ThenSaveButtonForLeadReasonIsEnabled() => Assert.Pass();

        [When(@"I leave one or more mandatory lead reason fields empty")]
        public void WhenILeaveOneOrMoreMandatoryLeadReasonFieldsEmpty() => Assert.Pass();

        [Then(@"Save button for lead reason is disabled")]
        public void ThenSaveButtonForLeadReasonIsDisabled() => Assert.Pass();
    }
}
