// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FraudCapture_BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Case Edit Functionality")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class CaseEditFunctionalityFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Case Edit Functionality", "  As a user of the FWA PI Portal\r\n  I want to be able to edit cases and manage ca" +
                "se activities\r\n  So that I can track and update case information effectively", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CaseEdit.Feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CaseEdit.Feature.ndjson", 15);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("1. Add Case Activity")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0804202614", "(DO NOT MODIFY) Automated Testing Inv Case Activity Manual", "Jha, Narottam", "0", null)]
        public async global::System.Threading.Tasks.Task _1_AddCaseActivity(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string investigativeCaseActivityManual_Title, string assignedTo, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("InvestigativeCaseActivityManual_Title", investigativeCaseActivityManual_Title);
            argumentsOfScenario.Add("AssignedTo", assignedTo);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("1. Add Case Activity", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table176 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table176.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 19
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table176, "When ");
#line hidden
#line 22
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table177 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table177.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 24
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table177, "And ");
#line hidden
                global::Reqnroll.Table table178 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table178.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 27
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table178, "And ");
#line hidden
                global::Reqnroll.Table table179 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table179.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 30
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table179, "And ");
#line hidden
                global::Reqnroll.Table table180 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table180.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 33
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table180, "And ");
#line hidden
#line 36
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
 await testRunner.AndAsync("the user shows activities", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table181 = new global::Reqnroll.Table(new string[] {
                            "InvestigativeCaseActivityManual_Title",
                            "AssignedTo"});
                table181.AddRow(new string[] {
                            string.Format("{0}", investigativeCaseActivityManual_Title),
                            string.Format("{0}", assignedTo)});
#line 40
 await testRunner.AndAsync("the user adds activity with title and assigned to", ((string)(null)), table181, "And ");
#line hidden
#line 43
 await testRunner.AndAsync("the user sorts activities by created date column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table182 = new global::Reqnroll.Table(new string[] {
                            "InvestigativeCaseActivityManual_Title"});
                table182.AddRow(new string[] {
                            string.Format("{0}", investigativeCaseActivityManual_Title)});
#line 44
 await testRunner.ThenAsync("the new activity should appear in the activities list", ((string)(null)), table182, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("2. Add Attachment To Lead Activity")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0804202614", "TestFile.txt", "1", null)]
        public async global::System.Threading.Tasks.Task _2_AddAttachmentToLeadActivity(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string attachmentTitle, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("AttachmentTitle", attachmentTitle);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("2. Add Attachment To Lead Activity", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table183 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table183.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 60
 await testRunner.WhenAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table183, "When ");
#line hidden
                global::Reqnroll.Table table184 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table184.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 63
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table184, "And ");
#line hidden
                global::Reqnroll.Table table185 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table185.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 66
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table185, "And ");
#line hidden
                global::Reqnroll.Table table186 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table186.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 69
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table186, "And ");
#line hidden
#line 72
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("the user shows activities", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.AndAsync("the user selects the first activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
 await testRunner.AndAsync("the user adds a new attachment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table187 = new global::Reqnroll.Table(new string[] {
                            "AttachmentTitle"});
                table187.AddRow(new string[] {
                            string.Format("{0}", attachmentTitle)});
#line 78
 await testRunner.ThenAsync("the new attachment should appear in the list", ((string)(null)), table187, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("3. Add Note To Case Activity")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0804202614", "Note added to Case Activity", "2", null)]
        public async global::System.Threading.Tasks.Task _3_AddNoteToCaseActivity(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string caseActivityManual_Title, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("CaseActivityManual_Title", caseActivityManual_Title);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("3. Add Note To Case Activity", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table188 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table188.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 94
 await testRunner.WhenAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table188, "When ");
#line hidden
                global::Reqnroll.Table table189 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table189.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 97
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table189, "And ");
#line hidden
                global::Reqnroll.Table table190 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table190.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 100
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table190, "And ");
#line hidden
                global::Reqnroll.Table table191 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table191.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 103
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table191, "And ");
#line hidden
#line 106
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.AndAsync("the user shows activities", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
 await testRunner.AndAsync("the user selects the first activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table192 = new global::Reqnroll.Table(new string[] {
                            "CaseActivityManual_Title"});
                table192.AddRow(new string[] {
                            string.Format("{0}", caseActivityManual_Title)});
#line 111
 await testRunner.AndAsync("the user adds a new note with text", ((string)(null)), table192, "And ");
#line hidden
                global::Reqnroll.Table table193 = new global::Reqnroll.Table(new string[] {
                            "CaseActivityManual_Title"});
                table193.AddRow(new string[] {
                            string.Format("{0}", caseActivityManual_Title)});
#line 114
 await testRunner.ThenAsync("the activity note should match", ((string)(null)), table193, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("4. Download From Activity Level Download Attachment Manager")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0108202513", "(DO NOT MODIFY) Automated Testing Inv Case Activity Manual", "3", null)]
        public async global::System.Threading.Tasks.Task _4_DownloadFromActivityLevelDownloadAttachmentManager(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string investigativeCaseActivityManual_Title, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("InvestigativeCaseActivityManual_Title", investigativeCaseActivityManual_Title);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("4. Download From Activity Level Download Attachment Manager", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 121
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 122
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table194 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table194.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 123
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table194, "When ");
#line hidden
#line 126
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table195 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table195.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 128
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table195, "And ");
#line hidden
                global::Reqnroll.Table table196 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table196.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 131
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table196, "And ");
#line hidden
                global::Reqnroll.Table table197 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table197.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 134
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table197, "And ");
#line hidden
                global::Reqnroll.Table table198 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table198.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 137
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table198, "And ");
#line hidden
#line 140
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 142
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
 await testRunner.AndAsync("the user shows activities", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
 await testRunner.AndAsync("the user selects the first activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
 await testRunner.AndAsync("the user adds a new attachment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
 await testRunner.AndAsync("the user downloads from activity level download attachment manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table199 = new global::Reqnroll.Table(new string[] {
                            "InvestigativeCaseActivityManual_Title"});
                table199.AddRow(new string[] {
                            string.Format("{0}", investigativeCaseActivityManual_Title)});
#line 147
 await testRunner.ThenAsync("the new download should appear in download attachment manager", ((string)(null)), table199, "Then ");
#line hidden
#line 150
 await testRunner.AndAsync("the user closes the activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("5. Download From Case Level Download Attachment Manager")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0108202513", "All", "4", null)]
        public async global::System.Threading.Tasks.Task _5_DownloadFromCaseLevelDownloadAttachmentManager(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string activityName_2, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("ActivityName_2", activityName_2);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("5. Download From Case Level Download Attachment Manager", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 156
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 157
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table200 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table200.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 158
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table200, "When ");
#line hidden
#line 161
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table201 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table201.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 163
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table201, "And ");
#line hidden
                global::Reqnroll.Table table202 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table202.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 166
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table202, "And ");
#line hidden
                global::Reqnroll.Table table203 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table203.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 169
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table203, "And ");
#line hidden
                global::Reqnroll.Table table204 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table204.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 172
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table204, "And ");
#line hidden
#line 175
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 177
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
 await testRunner.AndAsync("the user shows activities", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 179
 await testRunner.AndAsync("the user selects the first activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 180
 await testRunner.AndAsync("the user adds a new attachment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
 await testRunner.AndAsync("the user closes the activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 182
 await testRunner.AndAsync("the user downloads from case level download attachment manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table205 = new global::Reqnroll.Table(new string[] {
                            "ActivityName_2"});
                table205.AddRow(new string[] {
                            string.Format("{0}", activityName_2)});
#line 183
 await testRunner.ThenAsync("the new case download should appear in download attachment manager", ((string)(null)), table205, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("6. Verify Case Claims Clear Button Works")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0720202611", "Claim Number(s)", "201400238639", "5", null)]
        public async global::System.Threading.Tasks.Task _6_VerifyCaseClaimsClearButtonWorks(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string claimDropdownValue, string claimvalue1, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("ClaimDropdownValue", claimDropdownValue);
            argumentsOfScenario.Add("claimvalue1", claimvalue1);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("6. Verify Case Claims Clear Button Works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 191
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 192
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table206 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table206.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 193
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table206, "When ");
#line hidden
#line 196
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 197
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table207 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table207.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 198
 await testRunner.WhenAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table207, "When ");
#line hidden
                global::Reqnroll.Table table208 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table208.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 201
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table208, "And ");
#line hidden
                global::Reqnroll.Table table209 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table209.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 204
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table209, "And ");
#line hidden
                global::Reqnroll.Table table210 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table210.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 207
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table210, "And ");
#line hidden
#line 210
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 211
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 212
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 213
 await testRunner.AndAsync("the user clicks claims button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 214
 await testRunner.AndAsync("the user clicks case claim tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table211 = new global::Reqnroll.Table(new string[] {
                            "ClaimDropdownValue",
                            "claimvalue1"});
                table211.AddRow(new string[] {
                            string.Format("{0}", claimDropdownValue),
                            string.Format("{0}", claimvalue1)});
#line 215
 await testRunner.AndAsync("the user searches by case claim number with value", ((string)(null)), table211, "And ");
#line hidden
#line 218
 await testRunner.ThenAsync("the case claim search button should be enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("7. Verify Tooltip Appears Under Has Note Or Attachment Column")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0108202513", "Note added to Case Activity", "6", null)]
        public async global::System.Threading.Tasks.Task _7_VerifyTooltipAppearsUnderHasNoteOrAttachmentColumn(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string caseActivityManual_Title, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("CaseActivityManual_Title", caseActivityManual_Title);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("7. Verify Tooltip Appears Under Has Note Or Attachment Column", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 224
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table212 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table212.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 231
 await testRunner.WhenAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table212, "When ");
#line hidden
                global::Reqnroll.Table table213 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table213.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 234
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table213, "And ");
#line hidden
                global::Reqnroll.Table table214 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table214.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 237
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table214, "And ");
#line hidden
                global::Reqnroll.Table table215 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table215.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 240
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table215, "And ");
#line hidden
#line 243
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 244
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 245
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 246
 await testRunner.AndAsync("the user shows activities", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
 await testRunner.AndAsync("the user selects the first activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 248
 await testRunner.AndAsync("the user adds a new attachment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table216 = new global::Reqnroll.Table(new string[] {
                            "CaseActivityManual_Title"});
                table216.AddRow(new string[] {
                            string.Format("{0}", caseActivityManual_Title)});
#line 249
 await testRunner.AndAsync("the user adds a new note with text", ((string)(null)), table216, "And ");
#line hidden
#line 252
 await testRunner.AndAsync("the user closes the activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 253
 await testRunner.AndAsync("the user hovers over attachment and notes column", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 254
 await testRunner.ThenAsync("the attachment and notes column text should match", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 255
 await testRunner.WhenAsync("the user selects the first activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 256
 await testRunner.AndAsync("the user deletes the note", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 257
 await testRunner.AndAsync("the user closes the activity", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("8. Verify Findings Total Over Payments And Total Underpayments Displays Percentag" +
            "es Correctly")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0804202614", "Gainwell - FN Mali LN", "(DO NOT MODIFY) - Automated Testing Finding Reason Testing", "LOB1", "900", "700", "600", "2", "4", "7", "4", "Test Comments", "7", null)]
        public async global::System.Threading.Tasks.Task _8_VerifyFindingsTotalOverPaymentsAndTotalUnderpaymentsDisplaysPercentagesCorrectly(
                    string userEmail, 
                    string casesTab, 
                    string assignedToFilter, 
                    string caseTableSearchOptions, 
                    string caseID, 
                    string findingSubject, 
                    string findingReason, 
                    string lineOfBusiness, 
                    string underpaymentAmount, 
                    string overpaymentAmount, 
                    string softSavingAmount, 
                    string membersCount, 
                    string claimsCount, 
                    string linesCount, 
                    string providersCount, 
                    string comments, 
                    string @__pickleIndex, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("FindingSubject", findingSubject);
            argumentsOfScenario.Add("FindingReason", findingReason);
            argumentsOfScenario.Add("LineOfBusiness", lineOfBusiness);
            argumentsOfScenario.Add("UnderpaymentAmount", underpaymentAmount);
            argumentsOfScenario.Add("OverpaymentAmount", overpaymentAmount);
            argumentsOfScenario.Add("SoftSavingAmount", softSavingAmount);
            argumentsOfScenario.Add("MembersCount", membersCount);
            argumentsOfScenario.Add("ClaimsCount", claimsCount);
            argumentsOfScenario.Add("LinesCount", linesCount);
            argumentsOfScenario.Add("ProvidersCount", providersCount);
            argumentsOfScenario.Add("Comments", comments);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("8. Verify Findings Total Over Payments And Total Underpayments Displays Percentag" +
                    "es Correctly", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 263
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table217 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table217.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 270
 await testRunner.WhenAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table217, "When ");
#line hidden
                global::Reqnroll.Table table218 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table218.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 273
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table218, "And ");
#line hidden
                global::Reqnroll.Table table219 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table219.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 276
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table219, "And ");
#line hidden
                global::Reqnroll.Table table220 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table220.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 279
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table220, "And ");
#line hidden
#line 282
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 283
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 284
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 285
 await testRunner.AndAsync("the user begins editing case", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 286
 await testRunner.AndAsync("the user clicks findings tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table221 = new global::Reqnroll.Table(new string[] {
                            "Field",
                            "Value"});
                table221.AddRow(new string[] {
                            "FindingSubject",
                            string.Format("{0}", findingSubject)});
                table221.AddRow(new string[] {
                            "FindingReason",
                            string.Format("{0}", findingReason)});
                table221.AddRow(new string[] {
                            "LineOfBusiness",
                            string.Format("{0}", lineOfBusiness)});
                table221.AddRow(new string[] {
                            "UnderpaymentAmount",
                            string.Format("{0}", underpaymentAmount)});
                table221.AddRow(new string[] {
                            "OverpaymentAmount",
                            string.Format("{0}", overpaymentAmount)});
                table221.AddRow(new string[] {
                            "SoftSavingAmount",
                            string.Format("{0}", softSavingAmount)});
                table221.AddRow(new string[] {
                            "MembersCount",
                            string.Format("{0}", membersCount)});
                table221.AddRow(new string[] {
                            "ClaimsCount",
                            string.Format("{0}", claimsCount)});
                table221.AddRow(new string[] {
                            "LinesCount",
                            string.Format("{0}", linesCount)});
                table221.AddRow(new string[] {
                            "ProvidersCount",
                            string.Format("{0}", providersCount)});
                table221.AddRow(new string[] {
                            "Comments",
                            string.Format("{0}", comments)});
#line 287
 await testRunner.AndAsync("the user adds findings with the following details:", ((string)(null)), table221, "And ");
#line hidden
#line 300
 await testRunner.ThenAsync("the total underpayment value should be displayed correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 301
 await testRunner.AndAsync("the total overpayment value should be displayed correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 302
 await testRunner.AndAsync("the user deletes the findings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("9. Verify Claim Line Preview Functionality Works")]
        [global::NUnit.Framework.TestCaseAttribute("User_1", "Case_2", "8", null)]
        public async global::System.Threading.Tasks.Task _9_VerifyClaimLinePreviewFunctionalityWorks(string user, string caseID, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("User", user);
            argumentsOfScenario.Add("CaseID", caseID);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("9. Verify Claim Line Preview Functionality Works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 308
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 309
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table222 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table222.AddRow(new string[] {
                            "jayapradha.d@gainwelltechnologies.com"});
#line 310
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table222, "When ");
#line hidden
#line 313
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 314
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table223 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table223.AddRow(new string[] {
                            "Cases"});
#line 315
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table223, "And ");
#line hidden
                global::Reqnroll.Table table224 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table224.AddRow(new string[] {
                            "All"});
#line 318
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table224, "And ");
#line hidden
                global::Reqnroll.Table table225 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table225.AddRow(new string[] {
                            "Case ID"});
#line 321
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table225, "And ");
#line hidden
                global::Reqnroll.Table table226 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table226.AddRow(new string[] {
                            "DEMO0804202614"});
#line 324
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table226, "And ");
#line hidden
#line 327
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 328
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 329
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 330
 await testRunner.AndAsync("the user begins editing case", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 331
 await testRunner.AndAsync("the user clicks claims button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 332
 await testRunner.AndAsync("the user clicks case claim tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 333
 await testRunner.AndAsync("the user clicks on claim selector button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 334
 await testRunner.AndAsync("the user selects claims", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 335
 await testRunner.AndAsync("the user clicks case claim link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 336
 await testRunner.ThenAsync("the claim line preview popup should be displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("10. Verify Claim Line Preview Popup Column Names Are Not Repeated")]
        [global::NUnit.Framework.TestCaseAttribute("User_1", "Case_2", "9", null)]
        public async global::System.Threading.Tasks.Task _10_VerifyClaimLinePreviewPopupColumnNamesAreNotRepeated(string user, string caseID, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("User", user);
            argumentsOfScenario.Add("CaseID", caseID);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("10. Verify Claim Line Preview Popup Column Names Are Not Repeated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 342
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 343
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table227 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table227.AddRow(new string[] {
                            "jayapradha.d@gainwelltechnologies.com"});
#line 344
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table227, "When ");
#line hidden
#line 347
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 348
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table228 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table228.AddRow(new string[] {
                            "Cases"});
#line 349
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table228, "And ");
#line hidden
                global::Reqnroll.Table table229 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table229.AddRow(new string[] {
                            "All"});
#line 352
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table229, "And ");
#line hidden
                global::Reqnroll.Table table230 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table230.AddRow(new string[] {
                            "Case ID"});
#line 355
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table230, "And ");
#line hidden
                global::Reqnroll.Table table231 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table231.AddRow(new string[] {
                            "DEMO0804202614"});
#line 358
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table231, "And ");
#line hidden
#line 361
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 362
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 363
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 364
 await testRunner.AndAsync("the user begins editing case", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 365
 await testRunner.AndAsync("the user clicks claims button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 366
 await testRunner.AndAsync("the user clicks case claim tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 367
 await testRunner.AndAsync("the user clicks on claim selector button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 368
 await testRunner.AndAsync("the user selects claims", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 369
 await testRunner.AndAsync("the user clicks case claim link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 370
 await testRunner.ThenAsync("the case claim review popup column names should not be repeated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("11. Download Claims Detail And Validate Data")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0720202611", "201400238639", "10", null)]
        public async global::System.Threading.Tasks.Task _11_DownloadClaimsDetailAndValidateData(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string claimSummaryClaimIDforInvestigativecase, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("ClaimSummaryClaimIDforInvestigativecase", claimSummaryClaimIDforInvestigativecase);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("11. Download Claims Detail And Validate Data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 376
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 377
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table232 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table232.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 378
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table232, "When ");
#line hidden
#line 381
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 382
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table233 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table233.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 383
 await testRunner.WhenAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table233, "When ");
#line hidden
                global::Reqnroll.Table table234 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table234.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 386
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table234, "And ");
#line hidden
                global::Reqnroll.Table table235 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table235.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 389
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table235, "And ");
#line hidden
                global::Reqnroll.Table table236 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table236.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 392
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table236, "And ");
#line hidden
#line 395
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 396
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 397
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 398
 await testRunner.AndAsync("the user clicks claims button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 399
 await testRunner.AndAsync("the user clicks case claim tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 400
 await testRunner.AndAsync("the user downloads case claims detail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table237 = new global::Reqnroll.Table(new string[] {
                            "ClaimSummaryClaimIDforInvestigativecase"});
                table237.AddRow(new string[] {
                            string.Format("{0}", claimSummaryClaimIDforInvestigativecase)});
#line 401
 await testRunner.ThenAsync("the downloaded claim summary should match", ((string)(null)), table237, "Then ");
#line hidden
#line 404
 await testRunner.AndAsync("the user closes window handles", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("12. Can Run Patient Histories Report")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0720202611", "49279", "11", null)]
        public async global::System.Threading.Tasks.Task _12_CanRunPatientHistoriesReport(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string patientHistoriesReport_ExpectedData, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("PatientHistoriesReport_ExpectedData", patientHistoriesReport_ExpectedData);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("12. Can Run Patient Histories Report", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 410
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 411
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table238 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table238.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 412
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table238, "When ");
#line hidden
#line 415
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 416
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table239 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table239.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 417
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table239, "And ");
#line hidden
                global::Reqnroll.Table table240 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table240.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 420
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table240, "And ");
#line hidden
                global::Reqnroll.Table table241 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table241.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 423
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table241, "And ");
#line hidden
                global::Reqnroll.Table table242 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table242.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 426
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table242, "And ");
#line hidden
#line 429
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 430
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 431
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 432
 await testRunner.AndAsync("the user clicks claims button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 433
 await testRunner.AndAsync("the user clicks case claim tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 434
 await testRunner.AndAsync("the user runs patient histories report with expected data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table243 = new global::Reqnroll.Table(new string[] {
                            "PatientHistoriesReport_ExpectedData"});
                table243.AddRow(new string[] {
                            string.Format("{0}", patientHistoriesReport_ExpectedData)});
#line 435
 await testRunner.ThenAsync("the patient histories report should run successfully", ((string)(null)), table243, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("13. Download Excel Report And Verify Data Renders Properly")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0720202611", "49279", "12", null)]
        public async global::System.Threading.Tasks.Task _13_DownloadExcelReportAndVerifyDataRendersProperly(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string patientHistoriesReport_ExpectedData, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("PatientHistoriesReport_ExpectedData", patientHistoriesReport_ExpectedData);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("13. Download Excel Report And Verify Data Renders Properly", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 443
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 444
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table244 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table244.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 445
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table244, "When ");
#line hidden
#line 448
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 449
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table245 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table245.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 450
 await testRunner.WhenAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table245, "When ");
#line hidden
                global::Reqnroll.Table table246 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table246.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 453
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table246, "And ");
#line hidden
                global::Reqnroll.Table table247 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table247.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 456
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table247, "And ");
#line hidden
                global::Reqnroll.Table table248 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table248.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 459
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table248, "And ");
#line hidden
#line 462
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 463
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 464
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 465
 await testRunner.AndAsync("the user clicks claims button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 466
 await testRunner.AndAsync("the user clicks case claim tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 467
 await testRunner.AndAsync("the user downloads patient histories excel report with expected data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table249 = new global::Reqnroll.Table(new string[] {
                            "PatientHistoriesReport_ExpectedData"});
                table249.AddRow(new string[] {
                            string.Format("{0}", patientHistoriesReport_ExpectedData)});
#line 468
 await testRunner.ThenAsync("the excel report should be downloaded and data should render properly", ((string)(null)), table249, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
