// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FraudCapture_BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("FraudCapture_CreateNewCase")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class FraudCapture_CreateNewCaseFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "FraudCapture_CreateNewCase", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "FraudCapture_CaseEditTests.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/FraudCapture_CaseEditTests.feature.ndjson", 7);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("_01 Verify user is able to close lead by entering existing leadID and convert cas" +
            "e by selecting case details")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Leads", "All", "Lead ID", "(DO NOT MODIFY) Automated Lead Workflow", "Billing Errors", "D, Jayapradha", "D, Jayapradha", "SIU Group", "QA_Test", "DEMO0804202614", "DEMO0804202614", "Closed Lead - Case Created", "Close the Lead & Create a Case", "0", null)]
        public async global::System.Threading.Tasks.Task _01VerifyUserIsAbleToCloseLeadByEnteringExistingLeadIDAndConvertCaseBySelectingCaseDetails(
                    string userEmail, 
                    string leadsTab, 
                    string assignedToFilter, 
                    string leadTableSearchOptions, 
                    string caseWorkflowType, 
                    string caseReason, 
                    string assignWorkflowTo, 
                    string assignSupervisor, 
                    string depart_OR_Div, 
                    string section_OR_Team, 
                    string leadID, 
                    string caseID, 
                    string leadStatus, 
                    string closeLeadCreateCaseButton, 
                    string @__pickleIndex, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("LeadsTab", leadsTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("LeadTableSearchOptions", leadTableSearchOptions);
            argumentsOfScenario.Add("CaseWorkflowType", caseWorkflowType);
            argumentsOfScenario.Add("CaseReason", caseReason);
            argumentsOfScenario.Add("AssignWorkflowTo", assignWorkflowTo);
            argumentsOfScenario.Add("AssignSupervisor", assignSupervisor);
            argumentsOfScenario.Add("Depart_OR_Div", depart_OR_Div);
            argumentsOfScenario.Add("Section_OR_Team", section_OR_Team);
            argumentsOfScenario.Add("LeadID", leadID);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("LeadStatus", leadStatus);
            argumentsOfScenario.Add("CloseLeadCreateCaseButton", closeLeadCreateCaseButton);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("_01 Verify user is able to close lead by entering existing leadID and convert cas" +
                    "e by selecting case details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table371 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table371.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 7
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table371, "When ");
#line hidden
#line 10
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table372 = new global::Reqnroll.Table(new string[] {
                            "LeadsTab"});
                table372.AddRow(new string[] {
                            string.Format("{0}", leadsTab)});
#line 12
 await testRunner.AndAsync("I click on CaseTracking and select the required option on the fraud capture home " +
                        "page", ((string)(null)), table372, "And ");
#line hidden
                global::Reqnroll.Table table373 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table373.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 15
 await testRunner.AndAsync("I filter Assigned To Dropdown", ((string)(null)), table373, "And ");
#line hidden
                global::Reqnroll.Table table374 = new global::Reqnroll.Table(new string[] {
                            "LeadTableSearchOptions"});
                table374.AddRow(new string[] {
                            string.Format("{0}", leadTableSearchOptions)});
#line 18
 await testRunner.AndAsync("I search for leadID under Select Criteria dropdown", ((string)(null)), table374, "And ");
#line hidden
                global::Reqnroll.Table table375 = new global::Reqnroll.Table(new string[] {
                            "LeadID"});
                table375.AddRow(new string[] {
                            string.Format("{0}", leadID)});
#line 21
 await testRunner.AndAsync("I search for Lead ID", ((string)(null)), table375, "And ");
#line hidden
#line 24
 await testRunner.AndAsync("I click on Lead search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
 await testRunner.AndAsync("I click on the Lead ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table376 = new global::Reqnroll.Table(new string[] {
                            "LeadID"});
                table376.AddRow(new string[] {
                            string.Format("{0}", leadID)});
#line 26
 await testRunner.AndAsync("I verify the given Lead ID link is opened", ((string)(null)), table376, "And ");
#line hidden
#line 29
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Lead detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
 await testRunner.AndAsync("I store all lead summary dropdown values", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table377 = new global::Reqnroll.Table(new string[] {
                            "LeadStatus"});
                table377.AddRow(new string[] {
                            string.Format("{0}", leadStatus)});
#line 31
 await testRunner.AndAsync("I change the Lead Status dropdown", ((string)(null)), table377, "And ");
#line hidden
#line 34
 await testRunner.AndAsync("I validate Status Change and Case Creation popup is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table378 = new global::Reqnroll.Table(new string[] {
                            "CloseLeadCreateCaseButton"});
                table378.AddRow(new string[] {
                            string.Format("{0}", closeLeadCreateCaseButton)});
#line 35
 await testRunner.AndAsync("I click on Close the Lead & Create a Case button", ((string)(null)), table378, "And ");
#line hidden
                global::Reqnroll.Table table379 = new global::Reqnroll.Table(new string[] {
                            "CaseWorkflowType"});
                table379.AddRow(new string[] {
                            string.Format("{0}", caseWorkflowType)});
#line 38
 await testRunner.AndAsync("I select a case Workflow Type on the create case popup", ((string)(null)), table379, "And ");
#line hidden
                global::Reqnroll.Table table380 = new global::Reqnroll.Table(new string[] {
                            "CaseReason"});
                table380.AddRow(new string[] {
                            string.Format("{0}", caseReason)});
#line 41
 await testRunner.AndAsync("I select the primary Case Reason on the create case popup", ((string)(null)), table380, "And ");
#line hidden
                global::Reqnroll.Table table381 = new global::Reqnroll.Table(new string[] {
                            "AssignWorkflowTo"});
                table381.AddRow(new string[] {
                            string.Format("{0}", assignWorkflowTo)});
#line 44
 await testRunner.AndAsync("I select Assign workflow To on the create case popup", ((string)(null)), table381, "And ");
#line hidden
                global::Reqnroll.Table table382 = new global::Reqnroll.Table(new string[] {
                            "AssignSupervisor"});
                table382.AddRow(new string[] {
                            string.Format("{0}", assignSupervisor)});
#line 47
 await testRunner.AndAsync("I select assign a Supervisor on the create case popup", ((string)(null)), table382, "And ");
#line hidden
                global::Reqnroll.Table table383 = new global::Reqnroll.Table(new string[] {
                            "Depart_OR_Div"});
                table383.AddRow(new string[] {
                            "<Depart_OR_Div"});
#line 50
 await testRunner.AndAsync("I select a Department or Division on the create case popup", ((string)(null)), table383, "And ");
#line hidden
                global::Reqnroll.Table table384 = new global::Reqnroll.Table(new string[] {
                            "Section_OR_Team"});
                table384.AddRow(new string[] {
                            string.Format("{0}", section_OR_Team)});
#line 53
 await testRunner.AndAsync("I select a Section or Team on the create case popup", ((string)(null)), table384, "And ");
#line hidden
#line 56
 await testRunner.AndAsync("I click create case button on the create case popup", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table385 = new global::Reqnroll.Table(new string[] {
                            "LeadID"});
                table385.AddRow(new string[] {
                            string.Format("{0}", leadID)});
#line 57
 await testRunner.ThenAsync("I validate the created case is linked to the same lead id entered", ((string)(null)), table385, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("_02 Verify user is able to close lead by creating a new lead and convert case and" +
            " validate created case details")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "(DO NOT MODIFY) Automated Lead Workflow", "(DO NOT MODIFY) Automated Testing Detection Method", "(DO NOT MODIFY) Automated Testing Lead Source", "(DO NOT MODIFY) Automated Testing Lead Reason", "Chandrasekar, Yamuna", "Member", "Search by Address", "5615 High Point Dr", "Irving", "Test", "Manually add the Referring Party Details", "1", null)]
        public async global::System.Threading.Tasks.Task _02VerifyUserIsAbleToCloseLeadByCreatingANewLeadAndConvertCaseAndValidateCreatedCaseDetails(string userEmail, string workflowType, string detectionMethod, string sourceType, string reason, string assignedTo, string subjectType, string subjectTypeSelect, string addressField, string city, string description, string referringParty, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("WorkflowType", workflowType);
            argumentsOfScenario.Add("DetectionMethod", detectionMethod);
            argumentsOfScenario.Add("SourceType", sourceType);
            argumentsOfScenario.Add("Reason", reason);
            argumentsOfScenario.Add("AssignedTo", assignedTo);
            argumentsOfScenario.Add("SubjectType", subjectType);
            argumentsOfScenario.Add("SubjectTypeSelect", subjectTypeSelect);
            argumentsOfScenario.Add("addressField", addressField);
            argumentsOfScenario.Add("city", city);
            argumentsOfScenario.Add("Description", description);
            argumentsOfScenario.Add("ReferringParty", referringParty);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("_02 Verify user is able to close lead by creating a new lead and convert case and" +
                    " validate created case details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table386 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table386.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 68
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table386, "When ");
#line hidden
#line 71
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table387 = new global::Reqnroll.Table(new string[] {
                            "LeadsTab"});
                table387.AddRow(new string[] {
                            "<LeadsTab>"});
#line 73
 await testRunner.AndAsync("I click on CaseTracking and select the required option on the fraud capture home " +
                        "page", ((string)(null)), table387, "And ");
#line hidden
#line 76
 await testRunner.AndAsync("I click CreateNewLead button to go to Lead Creation Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table388 = new global::Reqnroll.Table(new string[] {
                            "WorkflowType",
                            "DetectionMethod",
                            "SourceType",
                            "Reason",
                            "AssignedTo"});
                table388.AddRow(new string[] {
                            string.Format("{0}", workflowType),
                            string.Format("{0}", detectionMethod),
                            string.Format("{0}", sourceType),
                            string.Format("{0}", reason),
                            string.Format("{0}", assignedTo)});
#line 77
 await testRunner.AndAsync("I enter initial user details in Lead Creation Tab:", ((string)(null)), table388, "And ");
#line hidden
#line 80
 await testRunner.AndAsync("I Click the Next button in the first page of CreateNewLead Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table389 = new global::Reqnroll.Table(new string[] {
                            "SubjectType",
                            "SubjectTypeSelect",
                            "addressField",
                            "city"});
                table389.AddRow(new string[] {
                            string.Format("{0}", subjectType),
                            string.Format("{0}", subjectTypeSelect),
                            string.Format("{0}", addressField),
                            string.Format("{0}", city)});
#line 81
 await testRunner.AndAsync("I enter Subject details in Primary Subject Tab for Search By Address:", ((string)(null)), table389, "And ");
#line hidden
#line 84
 await testRunner.AndAsync("I click Search button from the Search By Address screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.AndAsync("I giving the address to see the Case Details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
 await testRunner.AndAsync("I click on the Next button on the Primary Subject Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.AndAsync("I click Description tab in the Description Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table390 = new global::Reqnroll.Table(new string[] {
                            "Description"});
                table390.AddRow(new string[] {
                            string.Format("{0}", description)});
#line 88
 await testRunner.AndAsync("I enter Description details in Description tab:", ((string)(null)), table390, "And ");
#line hidden
#line 91
 await testRunner.AndAsync("I click on the Next button on the Description Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table391 = new global::Reqnroll.Table(new string[] {
                            "ReferringParty"});
                table391.AddRow(new string[] {
                            string.Format("{0}", referringParty)});
#line 92
 await testRunner.AndAsync("I enter Referring Party details in Referring Party tab:", ((string)(null)), table391, "And ");
#line hidden
#line 95
 await testRunner.AndAsync("I click on the Next button on the Referring Party Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
 await testRunner.AndAsync("I click Prioritization and click Create New Lead button in the Prioritization Pag" +
                        "e", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.AndAsync("Get the lead ID for the newly created lead", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
 await testRunner.ThenAsync("the lead with captured ID should be displayed in the search results", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table392 = new global::Reqnroll.Table(new string[] {
                            "LeadsTab"});
                table392.AddRow(new string[] {
                            "<LeadsTab>"});
#line 100
 await testRunner.WhenAsync("I click on CaseTracking and select the required option on the fraud capture home " +
                        "page", ((string)(null)), table392, "When ");
#line hidden
                global::Reqnroll.Table table393 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table393.AddRow(new string[] {
                            "<AssignedToFilter>"});
#line 103
 await testRunner.AndAsync("I filter Assigned To Dropdown", ((string)(null)), table393, "And ");
#line hidden
                global::Reqnroll.Table table394 = new global::Reqnroll.Table(new string[] {
                            "LeadTableSearchOptions"});
                table394.AddRow(new string[] {
                            "<LeadTableSearchOptions>"});
#line 106
 await testRunner.AndAsync("I search for leadID under Select Criteria dropdown", ((string)(null)), table394, "And ");
#line hidden
#line 109
 await testRunner.AndAsync("I search for Lead ID Created", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
 await testRunner.AndAsync("I click on Lead search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
 await testRunner.AndAsync("I click on the Lead ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
 await testRunner.AndAsync("I verify the Lead ID link is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Lead detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
 await testRunner.AndAsync("I store all lead summary dropdown values", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table395 = new global::Reqnroll.Table(new string[] {
                            "LeadStatus"});
                table395.AddRow(new string[] {
                            "<LeadStatus>"});
#line 115
 await testRunner.AndAsync("I change the Lead Status dropdown", ((string)(null)), table395, "And ");
#line hidden
#line 118
 await testRunner.AndAsync("I validate Status Change and Case Creation popup is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table396 = new global::Reqnroll.Table(new string[] {
                            "CloseLeadCreateCaseButton"});
                table396.AddRow(new string[] {
                            "<CloseLeadCreateCaseButton>"});
#line 119
 await testRunner.AndAsync("I click on Close the Lead & Create a Case button", ((string)(null)), table396, "And ");
#line hidden
                global::Reqnroll.Table table397 = new global::Reqnroll.Table(new string[] {
                            "CaseWorkflowType"});
                table397.AddRow(new string[] {
                            "<CaseWorkflowType>"});
#line 122
 await testRunner.AndAsync("I select a case Workflow Type on the create case popup", ((string)(null)), table397, "And ");
#line hidden
                global::Reqnroll.Table table398 = new global::Reqnroll.Table(new string[] {
                            "CaseReason"});
                table398.AddRow(new string[] {
                            "<CaseReason>"});
#line 125
 await testRunner.AndAsync("I select the primary Case Reason on the create case popup", ((string)(null)), table398, "And ");
#line hidden
                global::Reqnroll.Table table399 = new global::Reqnroll.Table(new string[] {
                            "AssignWorkflowTo"});
                table399.AddRow(new string[] {
                            "<AssignWorkflowTo>"});
#line 128
 await testRunner.AndAsync("I select Assign workflow To on the create case popup", ((string)(null)), table399, "And ");
#line hidden
                global::Reqnroll.Table table400 = new global::Reqnroll.Table(new string[] {
                            "AssignSupervisor"});
                table400.AddRow(new string[] {
                            "< AssignSupervisor>"});
#line 131
 await testRunner.AndAsync("I select assign a Supervisor on the create case popup", ((string)(null)), table400, "And ");
#line hidden
                global::Reqnroll.Table table401 = new global::Reqnroll.Table(new string[] {
                            "Depart_OR_Div"});
                table401.AddRow(new string[] {
                            "<Depart_OR_Div>"});
#line 134
 await testRunner.AndAsync("I select a Department or Division on the create case popup", ((string)(null)), table401, "And ");
#line hidden
                global::Reqnroll.Table table402 = new global::Reqnroll.Table(new string[] {
                            "Section_OR_Team"});
                table402.AddRow(new string[] {
                            "<Section_OR_Team>"});
#line 137
 await testRunner.AndAsync("I select a Section or Team on the create case popup", ((string)(null)), table402, "And ");
#line hidden
#line 140
 await testRunner.ThenAsync("I validate the created case is linked to the same lead id", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("_03 Edit case summary fields and save successfully and Validate the changes are r" +
            "eflected in the Case Summary Page")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0804202614", "ALT-DEMO0804202614", "Pharmacy", "Open - Investigation in Progress", "D, Jayapradha", "D, Jayapradha", "SIU Group", "QA_Test", "LOB1", "DEMO", "(DO NOT MODIFY) Automated Testing Inv Case Open", "(DO NOT MODIFY) Automated Investigative Workflow", "(Do Not Modify) Product Team", "LOB1", "2", null)]
        public async global::System.Threading.Tasks.Task _03EditCaseSummaryFieldsAndSaveSuccessfullyAndValidateTheChangesAreReflectedInTheCaseSummaryPage(
                    string userEmail, 
                    string casesTab, 
                    string assignedToFilter, 
                    string caseTableSearchOptions, 
                    string caseID, 
                    string aLT_Case_ID, 
                    string caseType, 
                    string caseStatus, 
                    string assignedCaseTo, 
                    string assignedCaseSupervisor, 
                    string caseDep_OR_Dev, 
                    string caseSection_OR_Team, 
                    string lob, 
                    string reassignALT_CaseID, 
                    string reassigncaseStatus, 
                    string reassign_CaseType, 
                    string reassign_Section_OR_Team, 
                    string uncheck_LOB, 
                    string @__pickleIndex, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("ALT_Case_ID", aLT_Case_ID);
            argumentsOfScenario.Add("CaseType", caseType);
            argumentsOfScenario.Add("CaseStatus", caseStatus);
            argumentsOfScenario.Add("AssignedCaseTo", assignedCaseTo);
            argumentsOfScenario.Add("AssignedCaseSupervisor", assignedCaseSupervisor);
            argumentsOfScenario.Add("CaseDep_OR_Dev", caseDep_OR_Dev);
            argumentsOfScenario.Add("CaseSection_OR_Team", caseSection_OR_Team);
            argumentsOfScenario.Add("lob", lob);
            argumentsOfScenario.Add("ReassignALT_CaseID", reassignALT_CaseID);
            argumentsOfScenario.Add("ReassigncaseStatus", reassigncaseStatus);
            argumentsOfScenario.Add("Reassign_CaseType", reassign_CaseType);
            argumentsOfScenario.Add("Reassign_Section_OR_Team", reassign_Section_OR_Team);
            argumentsOfScenario.Add("Uncheck_LOB", uncheck_LOB);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("_03 Edit case summary fields and save successfully and Validate the changes are r" +
                    "eflected in the Case Summary Page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 148
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 149
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table403 = new global::Reqnroll.Table(new string[] {
                            string.Format("{0}", userEmail)});
#line 150
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table403, "When ");
#line hidden
#line 152
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 153
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table404 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table404.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 154
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table404, "And ");
#line hidden
                global::Reqnroll.Table table405 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table405.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 157
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table405, "And ");
#line hidden
                global::Reqnroll.Table table406 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table406.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 160
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table406, "And ");
#line hidden
                global::Reqnroll.Table table407 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table407.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 163
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table407, "And ");
#line hidden
#line 166
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table408 = new global::Reqnroll.Table(new string[] {
                            "ALT_Case_ID",
                            "CaseType",
                            "CaseStatus",
                            "AssignedCaseTo",
                            "AssignedCaseSupervisor",
                            "CaseDep_OR_Dev",
                            "CaseSection_Or_Team",
                            "lob"});
                table408.AddRow(new string[] {
                            string.Format("{0}", aLT_Case_ID),
                            string.Format("{0}", caseType),
                            string.Format("{0}", caseStatus),
                            string.Format("{0}", assignedCaseTo),
                            string.Format("{0}", assignedCaseSupervisor),
                            string.Format("{0}", caseDep_OR_Dev),
                            string.Format("{0}", caseSection_OR_Team),
                            string.Format("{0}", lob)});
#line 169
 await testRunner.AndAsync("I update case summary with alternate case id,case type, case status, assigned to," +
                        " assigned supervisor, department_Or_division, section_Or_team, and lob", ((string)(null)), table408, "And ");
#line hidden
#line 172
 await testRunner.ThenAsync("I validate case summary changes are saved", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table409 = new global::Reqnroll.Table(new string[] {
                            "ReassignALT_CaseID",
                            "Reassign_CaseType",
                            "ReassigncaseStatus",
                            "Reassign_Section_OR_Team",
                            "Uncheck_LOB"});
                table409.AddRow(new string[] {
                            string.Format("{0}", reassignALT_CaseID),
                            string.Format("{0}", reassign_CaseType),
                            string.Format("{0}", reassigncaseStatus),
                            string.Format("{0}", reassign_Section_OR_Team),
                            string.Format("{0}", uncheck_LOB)});
#line 173
 await testRunner.WhenAsync("I remove all the added values alternate case id,case type, case status, section_O" +
                        "r_team, and lob", ((string)(null)), table409, "When ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("_04 Manually add a new subject to the case and validate the subject is added succ" +
            "essfully")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0804202614", "<SubjectType>", "<SubjectTypeSelect>", "<FirstName>", "<LastName>", "<NPI>", "<AddressField>", "<City>", "3", null)]
        public async global::System.Threading.Tasks.Task _04ManuallyAddANewSubjectToTheCaseAndValidateTheSubjectIsAddedSuccessfully(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string subjectType, string subjectTypeSelect, string firstName, string lastName, string nPI, string addressField, string city, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("SubjectType", subjectType);
            argumentsOfScenario.Add("SubjectTypeSelect", subjectTypeSelect);
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            argumentsOfScenario.Add("NPI", nPI);
            argumentsOfScenario.Add("AddressField", addressField);
            argumentsOfScenario.Add("City", city);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("_04 Manually add a new subject to the case and validate the subject is added succ" +
                    "essfully", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 182
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 183
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table410 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table410.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 184
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table410, "When ");
#line hidden
#line 187
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table411 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table411.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 189
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table411, "And ");
#line hidden
                global::Reqnroll.Table table412 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table412.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 192
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table412, "And ");
#line hidden
                global::Reqnroll.Table table413 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table413.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 195
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table413, "And ");
#line hidden
                global::Reqnroll.Table table414 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table414.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 198
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table414, "And ");
#line hidden
#line 201
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 202
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 203
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
 await testRunner.AndAsync("navigate to Subjects Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
 await testRunner.AndAsync("Manually add Subject Type as \"Provider\", select option as \"Manually add the Subje" +
                        "ct\" and enter the subject details in the manually add subject page: org name as " +
                        "\"TestOrg\", subject id as \"12345\", first name as \"John\", last name as \"Doe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("_05 Validate the subject first and last name and delete it if the passed subject " +
            "name is already present")]
        [global::NUnit.Framework.TestCaseAttribute("jayapradha.d@gainwelltechnologies.com", "Cases", "All", "Case ID", "DEMO0804202614", "John", "Doe", "4", null)]
        public async global::System.Threading.Tasks.Task _05ValidateTheSubjectFirstAndLastNameAndDeleteItIfThePassedSubjectNameIsAlreadyPresent(string userEmail, string casesTab, string assignedToFilter, string caseTableSearchOptions, string caseID, string firstName, string lastName, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("UserEmail", userEmail);
            argumentsOfScenario.Add("CasesTab", casesTab);
            argumentsOfScenario.Add("AssignedToFilter", assignedToFilter);
            argumentsOfScenario.Add("CaseTableSearchOptions", caseTableSearchOptions);
            argumentsOfScenario.Add("CaseID", caseID);
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("_05 Validate the subject first and last name and delete it if the passed subject " +
                    "name is already present", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 212
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 213
 await testRunner.GivenAsync("when I open the Fraud Capture application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table415 = new global::Reqnroll.Table(new string[] {
                            "UserEmail"});
                table415.AddRow(new string[] {
                            string.Format("{0}", userEmail)});
#line 214
 await testRunner.WhenAsync("I enter the UserEmail on the welcome fraude capture page:", ((string)(null)), table415, "When ");
#line hidden
#line 217
 await testRunner.AndAsync("I click on the Procced to login button on the welcome fraude capture page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 218
 await testRunner.AndAsync("I click on the I Agree button on the fraud capture Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table416 = new global::Reqnroll.Table(new string[] {
                            "CasesTab"});
                table416.AddRow(new string[] {
                            string.Format("{0}", casesTab)});
#line 219
 await testRunner.AndAsync("I click on CaseTracking and select the Case option on the fraud capture home page" +
                        "", ((string)(null)), table416, "And ");
#line hidden
                global::Reqnroll.Table table417 = new global::Reqnroll.Table(new string[] {
                            "AssignedToFilter"});
                table417.AddRow(new string[] {
                            string.Format("{0}", assignedToFilter)});
#line 222
 await testRunner.AndAsync("I filter Assigned To Case Dropdown", ((string)(null)), table417, "And ");
#line hidden
                global::Reqnroll.Table table418 = new global::Reqnroll.Table(new string[] {
                            "CaseTableSearchOptions"});
                table418.AddRow(new string[] {
                            string.Format("{0}", caseTableSearchOptions)});
#line 225
 await testRunner.AndAsync("I search for caseID under Select Criteria dropdown", ((string)(null)), table418, "And ");
#line hidden
                global::Reqnroll.Table table419 = new global::Reqnroll.Table(new string[] {
                            "CaseID"});
                table419.AddRow(new string[] {
                            string.Format("{0}", caseID)});
#line 228
 await testRunner.AndAsync("I search for Case ID", ((string)(null)), table419, "And ");
#line hidden
#line 231
 await testRunner.AndAsync("I click on Case search button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 232
 await testRunner.AndAsync("I click on the Case ID Link", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 233
 await testRunner.AndAsync("I click on the Begin Editing on the fraud capture Case detials Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
 await testRunner.AndAsync("navigate to Subjects Tab", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
 await testRunner.ThenAsync(string.Format("I validate the subject \"{0}\" \"{1}\" is present and delete it if already present", firstName, lastName), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 236
 await testRunner.WhenAsync("Manually add Subject Type as \"Provider\", select option as \"Manually add the Subje" +
                        "ct\" and enter the subject details in the manually add subject page: org name as " +
                        "\"TestOrg\", subject id as \"12345\", first name as \"John\", last name as \"Doe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 237
 await testRunner.ThenAsync(string.Format("validate newly added subject \"{0}\" \"{1}\" is present in the subject table", firstName, lastName), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
